package ro.iss.lolopay.models.classes;

public enum DocumentType {
  IDENTITY_PROOF,
  REGISTRATION_PROOF,
  ADDRESS_PROOF,
  ARTICLES_OF_ASSOCIATION,
  SHAREHOLDER_DECLARATION,
  COMPANY_STATUTE,
  UBO_DECLARATION
}
