package ro.iss.lolopay.models.classes;

public enum DocumentRejectReason {
  DOCUMENT_UNREADABLE, //
  DOCUMENT_NOT_ACCEPTED, //
  DOCUMENT_HAS_EXPIRED, //
  DOCUMENT_INCOMPLETE, //
  DOCUMENT_MISSING, //
  DOCUMENT_DO_NOT_MATCH_USER_DATA, //
  DOCUMENT_DO_NOT_MATCH_ACCOUNT_DATA, //
  SPECIFIC_CASE, //
  DOCUMENT_FALSIFIED, //
  UNDERAGE_PERSON, //
  OTHER, //
  TRIGGER_PEPS, //
  TRIGGER_SANCTIONS_LISTS, //
  TRIGGER_INTERPOL
}
