package ro.iss.lolopay.models.classes;

public enum ProviderOperation {
  PAYIN,
  PAYOUT,
  TRANSFER,
  REFUND, //
  CREATEUSER,
  CREATELEGALUSER,
  SAVEUSER,
  SAVELEGALUSER,
  GETUSER, //
  CREATEWALLET, //
  CREATEDOCUMENT,
  CERATEDOCUMENTPAGE,
  SUBMITDOCUMENT,
  GETDOCUMENT, //
  CREATEUBODECLARATION,
  CREATEUBO,
  SUBMITUBODECLARATION,
  UPDATEUBO,
  VIEWUBODECLARATION,
  VIEWUBO,
  LISTUBODECLARATIONS, //
  CREATEBANKACCOUNT,
  DEACTIVATEBANKACCOUNT, //
  CREATEBANKCARD,
  GETCARD,
  UPGRADEBANKCARD,
  CHANGECARDSTATUS,
  ADDCARDCURRENCY,
  GETCARDWALLET, //
  GETCARDWALLETTRANSACTIONS,
  GETCARDNUMBER,
  GETCARDEXPDATE,
  GETCARDCVV,
  TRANSFERTOCARD, //
  SENDCARDPIN,
  LOCKUNLOCKCARD,
  TRANSFERFROMCARD,
  UPDATEBANKCARD, //
  EXECUTEBANKPAYMENT,
  GETFXQUOTE,
  FXTRADE,
  REPLACECARD, //
  CREATECARDREGISTRATION,
  UPDATECARDREGISTRATION,
  GETDEPOSITCARD, //
  DIRECTPAYIN,
  DEACTIVATEDEPOSITCARD, //
  GETUSERSDISPUTES,
  GETWALLET
}
