package ro.iss.lolopay.enums;

public class ErrorMessage {
  public static final String ERROR_CLIENT = "ERROR_CLIENT";

  public static final String ERROR_SERVER = "ERROR_SERVER";

  public static final String ERROR_PROVIDER = "ERROR_PROVIDER";

  public static final String ERROR_SERVER_CANNOT_SAVE_FILE = "ERROR_SERVER_CANNOT_SAVE_FILE";

  public static final String ERROR_INVALID_REQUEST_BODY = "ERROR_INVALID_REQUEST_BODY";

  public static final String ERROR_INVALID_TYPE_USED = "ERROR_INVALID_TYPE_USED";

  public static final String ERROR_HEADER_REQUESTID_MISSING = "ERROR_HEADER_REQUESTID_MISSING";

  public static final String ERROR_HEADER_REQUESTID_INVALID = "ERROR_HEADER_REQUESTID_INVALID";

  public static final String ERROR_HEADER_REQUESTID_DUPLICATED =
      "ERROR_HEADER_REQUESTID_DUPLICATED";

  public static final String ERROR_HEADER_USERAGENT_MISSING = "ERROR_HEADER_USERAGENT_MISSING";

  /** Authorisation errors */
  public static final String ERROR_AUTHORIZATION_HEADER_MISSING =
      "ERROR_AUTHORIZATION_HEADER_MISSING";

  public static final String ERROR_AUTHORIZATION_TOKEN_INVALID_OR_EXPIRED =
      "ERROR_AUTHORIZATION_TOKEN_INVALID_OR_EXPIRED";

  public static final String ERROR_AUTHORIZATION_TOKEN_INCOMPLETE =
      "ERROR_AUTHORIZATION_TOKEN_INCOMPLETE";

  public static final String ERROR_AUTHORIZATION_SESSION_EXPIRED =
      "ERROR_AUTHORIZATION_SESSION_EXPIRED";

  public static final String ERROR_AUTHORIZATION_TOKEN_FAILED_SECURITY =
      "ERROR_AUTHORIZATION_TOKEN_FAILED_SECURITY";

  public static final String ERROR_AUTHORIZATION_OPERATION_NOT_ALLOWED =
      "ERROR_AUTHORIZATION_OPERATION_NOT_ALLOWED";

  public static final String ERROR_AUTHORIZATION_INEXISTENT_ACCOUNT =
      "ERROR_AUTHORIZATION_INEXISTENT_ACCOUNT";

  public static final String ERROR_AUTHORIZATION_INEXISTENT_APPLICATION =
      "ERROR_AUTHORIZATION_INEXISTENT_APPLICATION";

  public static final String ERROR_AUTHORIZATION_APPLICATION_BLOCKED =
      "ERROR_AUTHORIZATION_APPLICATION_BLOCKED";

  /** Nested classes errors */
  public static final String ERROR_ADDRESS_LINE1_REQUIRED = "ERROR_ADDRESS_LINE1_REQUIRED";

  public static final String ERROR_ADDRESS_LINE1_MAXLENGTH = "ERROR_ADDRESS_LINE1_MAXLENGTH";

  public static final String ERROR_ADDRESS_LINE1_INVALID = "ERROR_ADDRESS_LINE1_INVALID";

  public static final String ERROR_ADDRESS_LINE2_MAXLENGTH = "ERROR_ADDRESS_LINE2_MAXLENGTH";

  public static final String ERROR_ADDRESS_CITY_REQUIRED = "ERROR_ADDRESS_CITY_REQUIRED";

  public static final String ERROR_ADDRESS_CITY_MAXLENGTH = "ERROR_ADDRESS_CITY_MAXLENGTH";

  public static final String ERROR_ADDRESS_COUNTY_REQUIRED = "ERROR_ADDRESS_COUNTY_REQUIRED";

  public static final String ERROR_ADDRESS_COUNTY_MAXLENGTH = "ERROR_ADDRESS_COUNTY_MAXLENGTH";

  public static final String ERROR_ADDRESS_COUNTRY_REQUIRED = "ERROR_ADDRESS_COUNTRY_REQUIRED";

  public static final String ERROR_ADDRESS_COUNTRY_INVALID = "ERROR_ADDRESS_COUNTRY_INVALID";

  public static final String ERROR_ADDRESS_POSTALCODE_REQUIRED =
      "ERROR_ADDRESS_POSTALCODE_REQUIRED";

  public static final String ERROR_ADDRESS_POSTALCODE_MAXLENGTH =
      "ERROR_ADDRESS_POSTALCODE_MAXLENGTH";

  public static final String ERROR_AMOUNT_VALUE_REQUIRED = "ERROR_AMOUNT_VALUE_REQUIRED";

  public static final String ERROR_AMOUNT_CURRENCY_REQUIRED = "ERROR_AMOUNT_CURRENCY_REQUIRED";

  public static final String ERROR_AMOUNT_CURRENCY_INVALID = "ERROR_AMOUNT_CURRENCY_INVALID";

  public static final String ERROR_AMOUNT_INVALID = "ERROR_AMOUNT_INVALID";

  public static final String ERROR_BIRTHPLACE_CITY_REQUIRED = "ERROR_BIRTHPLACE_CITY_REQUIRED";

  public static final String ERROR_BIRTHPLACE_CITY_MAXLENGTH = "ERROR_BIRTHPLACE_CITY_MAXLENGTH";

  public static final String ERROR_BIRTHPLACE_COUNTRY_REQUIRED =
      "ERROR_BIRTHPLACE_COUNTRY_REQUIRED";

  public static final String ERROR_BIRTHPLACE_COUNTRY_INVALID = "ERROR_BIRTHPLACE_COUNTRY_INVALID";

  /** Hook errors */
  public static final String ERROR_HOOKS_UNKNOWN_EVENT = "ERROR_HOOKS_UNKNOWN_EVENT";

  public static final String ERROR_HOOKS_RECORD_NOT_FOUND = "ERROR_HOOKS_RECORD_NOT_FOUND";

  public static final String ERROR_HOOKS_NOT_SENT_TO_CLIENT = "ERROR_HOOKS_NOT_SENT_TO_CLIENT";

  public static final String ERROR_HOOKS_INVALID_RECORD_STATUS =
      "ERROR_HOOKS_INVALID_RECORD_STATUS";

  public static final String ERROR_HOOKS_PROCESS_STOPPED = "ERROR_HOOKS_PROCESS_STOPPED";

  public static final String ERROR_HOOKS_INVALID_PROVIDER = "ERROR_HOOKS_INVALID_PROVIDER";

  /** Controller errors */
  public static final String ERROR_LOGIN_ACCOUNTID_REQUIRED = "ERROR_LOGIN_ACCOUNTID_REQUIRED";

  public static final String ERROR_LOGIN_ACCOUNTID_INVALID = "ERROR_LOGIN_ACCOUNTID_INVALID";

  public static final String ERROR_LOGIN_APPID_REQUIRED = "ERROR_LOGIN_APPID_REQUIRED";

  public static final String ERROR_LOGIN_APPID_INVALID = "ERROR_LOGIN_APPID_INVALID";

  public static final String ERROR_LOGIN_PASSWORD_REQUIRED = "ERROR_LOGIN_PASSWORD_REQUIRED";

  public static final String ERROR_LOGIN_INVALID_CREDENTIALS = "ERROR_LOGIN_INVALID_CREDENTIALS";

  /** CREATE NATURAL USER */
  public static final String ERROR_CREATEUSER_EMAIL_REQUIRED = "ERROR_CREATEUSER_EMAIL_REQUIRED";

  public static final String ERROR_CREATEUSER_EMAIL_MAXLENGTH = "ERROR_CREATEUSER_EMAIL_MAXLENGTH";

  public static final String ERROR_CREATEUSER_EMAIL_INVALID = "ERROR_CREATEUSER_EMAIL_INVALID";

  public static final String ERROR_CREATEUSER_FNAME_REQUIRED = "ERROR_CREATEUSER_FNAME_REQUIRED";

  public static final String ERROR_CREATEUSER_FNAME_MAXLENGTH = "ERROR_CREATEUSER_FNAME_MAXLENGTH";

  public static final String ERROR_CREATEUSER_LNAME_REQUIRED = "ERROR_CREATEUSER_LNAME_REQUIRED";

  public static final String ERROR_CREATEUSER_LNAME_MAXLENGTH = "ERROR_CREATEUSER_LNAME_MAXLENGTH";

  public static final String ERROR_CREATEUSER_BDATE_REQUIRED = "ERROR_CREATEUSER_BDATE_REQUIRED";

  public static final String ERROR_CREATEUSER_BDATE_INVALID = "ERROR_CREATEUSER_BDATE_INVALID";

  public static final String ERROR_CREATEUSER_NATIONALITY_REQUIRED =
      "ERROR_CREATEUSER_NATIONALITY_REQUIRED";

  public static final String ERROR_CREATEUSER_NATIONALITY_INVALID =
      "ERROR_CREATEUSER_NATIONALITY_INVALID";

  public static final String ERROR_CREATEUSER_COUNTRY_REQUIRED =
      "ERROR_CREATEUSER_COUNTRY_REQUIRED";

  public static final String ERROR_CREATEUSER_COUNTRY_INVALID = "ERROR_CREATEUSER_COUNTRY_INVALID";

  public static final String ERROR_CREATEUSER_TAG_MAXLENGTH = "ERROR_CREATEUSER_TAG_MAXLENGTH";

  public static final String ERROR_CREATEUSER_OCCUPATION_MAXLENGTH =
      "ERROR_CREATEUSER_OCCUPATION_MAXLENGTH";

  public static final String ERROR_CREATEUSER_MOBILEPHONE_REQUIRED =
      "ERROR_CREATEUSER_MOBILEPHONE_REQUIRED";

  public static final String ERROR_CREATEUSER_MOBILEPHONE_MAXLENGTH =
      "ERROR_CREATEUSER_MOBILEPHONE_MAXLENGTH";

  public static final String ERROR_CREATEUSER_USERTYPE_REQUIRED =
      "ERROR_CREATEUSER_USERTYPE_REQUIRED";

  public static final String ERROR_CREATEUSER_NATIONALITY_MAXLENGTH =
      "ERROR_CREATEUSER_NATIONALITY_MAXLENGTH";

  public static final String ERROR_CREATEUSER_COUNTRY_MAXLENGTH =
      "ERROR_CREATEUSER_COUNTRY_MAXLENGTH";

  public static final String ERROR_CREATEUSER_INCOME_RANGE_INVALID =
      "ERROR_CREATEUSER_INCOME_RANGE_INVALID";

  /** SAVE NATURAL USER */
  public static final String ERROR_SAVEUSER_ID_REQUIRED = "ERROR_SAVEUSER_ID_REQUIRED";

  public static final String ERROR_SAVEUSER_ID_INVALID = "ERROR_SAVEUSER_ID_INVALID";

  public static final String ERROR_SAVEUSER_EMAIL_MAXLENGTH = "ERROR_SAVEUSER_EMAIL_MAXLENGTH";

  public static final String ERROR_SAVEUSER_EMAIL_INVALID = "ERROR_SAVEUSER_EMAIL_INVALID";

  public static final String ERROR_SAVEUSER_FNAME_MAXLENGTH = "ERROR_SAVEUSER_FNAME_MAXLENGTH";

  public static final String ERROR_SAVEUSER_LNAME_MAXLENGTH = "ERROR_SAVEUSER_LNAME_MAXLENGTH";

  public static final String ERROR_SAVEUSER_BDATE_INVALID = "ERROR_SAVEUSER_BDATE_INVALID";

  public static final String ERROR_SAVEUSER_TAG_MAXLENGTH = "ERROR_SAVEUSER_TAG_MAXLENGTH";

  public static final String ERROR_SAVEUSER_OCCUPATION_MAXLENGTH =
      "ERROR_SAVEUSER_OCCUPATION_MAXLENGTH";

  public static final String ERROR_SAVEUSER_INEXISTENT_USER = "ERROR_SAVEUSER_INEXISTENT_USER";

  public static final String ERROR_SAVEUSER_MOBILEPHONE_MAXLENGTH =
      "ERROR_SAVEUSER_MOBILEPHONE_MAXLENGTH";

  public static final String ERROR_SAVEUSER_NATIONALITY_INVALID =
      "ERROR_SAVEUSER_NATIONALITY_INVALID";

  public static final String ERROR_SAVEUSER_COUNTRY_INVALID = "ERROR_SAVEUSER_COUNTRY_INVALID";

  public static final String ERROR_SAVEUSER_USERTYPE_INVALID = "ERROR_SAVEUSER_USERTYPE_INVALID";

  public static final String ERROR_SAVEUSER_INCOME_RANGE_INVALID =
      "ERROR_SAVEUSER_INCOME_RANGE_INVALID";

  public static final String ERROR_SAVEUSER_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_SAVEUSER_USER_NOT_REGISTERED2PROVIDER";

  /** CREATE LEGAL USER */
  public static final String ERROR_CREATELEGALUSER_COMPANYNAME_REQUIRED =
      "ERROR_CREATELEGALUSER_COMPANYNAME_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_COMPANYNAME_MAXLENGTH =
      "ERROR_CREATELEGALUSER_COMPANYNAME_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_COMPANYTYPE_INVALID =
      "ERROR_CREATELEGALUSER_COMPANYTYPE_INVALID";

  public static final String ERROR_CREATELEGALUSER_COUNTRY_REQUIRED =
      "ERROR_CREATELEGALUSER_COUNTRY_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_COUNTRY_MAXLENGTH =
      "ERROR_CREATELEGALUSER_COUNTRY_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_NATIONALITY_REQUIRED =
      "ERROR_CREATELEGALUSER_NATIONALITY_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_NATIONALITY_MAXLENGTH =
      "ERROR_CREATELEGALUSER_NATIONALITY_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_FNAME_REQUIRED =
      "ERROR_CREATELEGALUSER_FNAME_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_FNAME_MAXLENGTH =
      "ERROR_CREATELEGALUSER_FNAME_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_LNAME_REQUIRED =
      "ERROR_CREATELEGALUSER_LNAME_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_BDATE_REQUIRED =
      "ERROR_CREATELEGALUSER_BDATE_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_BDATE_INVALID =
      "ERROR_CREATELEGALUSER_BDATE_INVALID";

  public static final String ERROR_CREATELEGALUSER_LNAME_MAXLENGTH =
      "ERROR_CREATELEGALUSER_LNAME_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_MOBILEPHONE_REQUIRED =
      "ERROR_CREATELEGALUSER_MOBILEPHONE_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_MOBILEPHONE_MAXLENGTH =
      "ERROR_CREATELEGALUSER_MOBILEPHONE_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_COMPANYEMAIL_REQUIRED =
      "ERROR_CREATELEGALUSER_COMPANYEMAIL_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_COMPANYEMAIL_MAXLENGTH =
      "ERROR_CREATELEGALUSER_COMPANYEMAIL_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_EMAIL_INVALID =
      "ERROR_CREATELEGALUSER_EMAIL_INVALID";

  public static final String ERROR_CREATELEGALUSER_EMAIL_REQUIRED =
      "ERROR_CREATELEGALUSER_EMAIL_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_EMAIL_MAXLENGTH =
      "ERROR_CREATELEGALUSER_EMAIL_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_TAG_MAXLENGTH =
      "ERROR_CREATELEGALUSER_TAG_MAXLENGTH";

  public static final String ERROR_CREATELEGALUSER_COMPANYTYPE_REQUIRED =
      "ERROR_CREATELEGALUSER_COMPANYTYPE_REQUIRED";

  public static final String ERROR_CREATELEGALUSER_NATIONALITY_INVALID =
      "ERROR_CREATELEGALUSER_NATIONALITY_INVALID";

  public static final String ERROR_CREATELEGALUSER_COUNTRY_INVALID =
      "ERROR_CREATELEGALUSER_COUNTRY_INVALID";

  public static final String ERROR_CREATELEGALUSER_COMPANY_REGISTRATION_NUMBER_INVALID =
      "ERROR_CREATELEGALUSER_COMPANY_REGISTRATION_NUMBER_INVALID";

  /** SAVE LEGAL USER */
  public static final String ERROR_SAVELEGALUSER_ID_REQUIRED = "ERROR_SAVELEGALUSER_ID_REQUIRED";

  public static final String ERROR_SAVELEGALUSER_ID_INVALID = "ERROR_SAVELEGALUSER_ID_INVALID";

  public static final String ERROR_SAVELEGALUSER_INEXISTENT_USER =
      "ERROR_SAVELEGALUSER_INEXISTENT_USER";

  public static final String ERROR_SAVELEGALUSER_COMPANYTYPE_INVALID =
      "ERROR_SAVELEGALUSER_COMPANYTYPE_INVALID";

  public static final String ERROR_SAVELEGALUSER_COMPANYNAME = "ERROR_SAVELEGALUSER_COMPANYNAME";

  public static final String ERROR_SAVELEGALUSER_COUNTRY_MAXLENGTH =
      "ERROR_SAVELEGALUSER_COUNTRY_MAXLENGTH";

  public static final String ERROR_SAVELEGALUSER_NATIONALITY_MAXLENGTH =
      "ERROR_SAVELEGALUSER_NATIONALITY_MAXLENGTH";

  public static final String ERROR_SAVELEGALUSER_FNAME_MAXLENGTH =
      "ERROR_SAVELEGALUSER_FNAME_MAXLENGTH";

  public static final String ERROR_SAVELEGALUSER_LNAME_MAXLENGTH =
      "ERROR_SAVELEGALUSER_LNAME_MAXLENGTH";

  public static final String ERROR_SAVELEGALUSER_BDATE_INVALID =
      "ERROR_SAVELEGALUSER_BDATE_INVALID";

  public static final String ERROR_SAVELEGALUSER_MOBILEPHONE_MAXLENGTH =
      "ERROR_SAVELEGALUSER_MOBILEPHONE_MAXLENGTH";

  public static final String ERROR_SAVELEGALUSER_COMPANYEMAIL_MAXLENGTH =
      "ERROR_SAVELEGALUSER_COMPANYEMAIL_MAXLENGTH";

  public static final String ERROR_SAVELEGALUSER_COMPANYEMAIL_INVALID =
      "ERROR_SAVELEGALUSER_COMPANYEMAIL_INVALID";

  public static final String ERROR_SAVELEGALUSER_EMAIL_MAXLENGTH =
      "ERROR_SAVELEGALUSER_EMAIL_MAXLENGTH";

  public static final String ERROR_SAVELEGALUSER_EMAIL_INVALID =
      "ERROR_SAVELEGALUSER_EMAIL_INVALID";

  public static final String ERROR_SAVELEGALUSER_TAG_MAXLENGTH =
      "ERROR_SAVELEGALUSER_TAG_MAXLENGTH";

  public static final String ERROR_SAVELEGALUSER_USERTYPE_INVALID =
      "ERROR_SAVELEGALUSER_USERTYPE_INVALID";

  public static final String ERROR_SAVELEGALUSER_COUNTRY_INVALID =
      "ERROR_SAVELEGALUSER_COUNTRY_INVALID";

  public static final String ERROR_SAVELEGALUSER_NATIONALITY_INVALID =
      "ERROR_SAVELEGALUSER_NATIONALITY_INVALID";

  public static final String ERROR_SAVELEGALUSER_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_SAVELEGALUSER_USER_NOT_REGISTERED2PROVIDER";

  /** GET USER */
  public static final String ERROR_GETUSER_INVALID_USERID = "ERROR_GETUSER_INVALID_USERID";

  public static final String ERROR_GETUSER_INEXISTENT_USER = "ERROR_GETUSER_INEXISTENT_USER";

  /** TRANSFER */
  public static final String ERROR_CREATETRANSFER_DEBITWALLETID_REQUIRED =
      "ERROR_CREATETRANSFER_DEBITWALLETID_REQUIRED";

  public static final String ERROR_CREATETRANSFER_DEBITWALLETID_INVALID =
      "ERROR_CREATETRANSFER_DEBITWALLETID_INVALID";

  public static final String ERROR_CREATETRANSFER_DEBITWALLET_INEXISTENT =
      "ERROR_CREATETRANSFER_DEBITWALLET_INEXISTENT";

  public static final String ERROR_CREATETRANSFER_DEBITWALLET_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATETRANSFER_DEBITWALLET_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATETRANSFER_DEBITUSER_INEXISTENT =
      "ERROR_CREATETRANSFER_DEBITUSER_INEXISTENT";

  public static final String ERROR_CREATETRANSFER_DEBITUSERID_NOT_MATCHING_AUTHORID =
      "ERROR_CREATETRANSFER_DEBITUSERID_NOT_MATCHING_AUTHORID";

  public static final String ERROR_CREATETRANSFER_DEBITUSER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATETRANSFER_DEBITUSER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATETRANSFER_CREDITWALLETID_REQUIRED =
      "ERROR_CREATETRANSFER_CREDITWALLETID_REQUIRED";

  public static final String ERROR_CREATETRANSFER_CREDITWALLETID_INVALID =
      "ERROR_CREATETRANSFER_CREDITWALLETID_INVALID";

  public static final String ERROR_CREATETRANSFER_CREDITWALLET_INEXISTENT =
      "ERROR_CREATETRANSFER_CREDITWALLET_INEXISTENT";

  public static final String ERROR_CREATETRANSFER_CREDITWALLET_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATETRANSFER_CREDITWALLET_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATETRANSFER_CREDITUSER_INEXISTENT =
      "ERROR_CREATETRANSFER_CREDITUSER_INEXISTENT";

  public static final String ERROR_CREATETRANSFER_CREDITUSER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATETRANSFER_CREDITUSER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATETRANSFER_DEBITFUNDS_REQUIRED =
      "ERROR_CREATETRANSFER_DEBITFUNDS_REQUIRED";

  public static final String ERROR_CREATETRANSFER_FEES_REQUIRED =
      "ERROR_CREATETRANSFER_FEES_REQUIRED";

  public static final String ERROR_CREATETRANSFER_FEEMODEL_REQUIRED =
      "ERROR_CREATETRANSFER_FEEMODEL_REQUIRED";

  public static final String ERROR_CREATETRANSFER_FEEMODEL_INVALID =
      "ERROR_CREATETRANSFER_FEEMODEL_INVALID";

  public static final String ERROR_CREATETRANSFER_TAG_MAXLENGTH =
      "ERROR_CREATETRANSFER_TAG_MAXLENGTH";

  public static final String ERROR_CREATETRANSFER_WALLET_CURRENCY_MISSMATCH =
      "ERROR_CREATETRANSFER_WALLET_CURRENCY_MISSMATCH";

  public static final String ERROR_CREATETRANSFER_REQUEST_CURRENCY_MISSMATCH =
      "ERROR_CREATETRANSFER_REQUEST_CURRENCY_MISSMATCH";

  public static final String ERROR_CREATETRANSFER_REQUEST_AMOUNT_SMALLER_THAN_FEE =
      "ERROR_CREATETRANSFER_REQUEST_AMOUNT_SMALLER_THAN_FEE";

  public static final String ERROR_CREATETRANSFER_REQUEST_CURRENCY_INVALID =
      "ERROR_CREATETRANSFER_REQUEST_CURRENCY_INVALID";

  public static final String ERROR_CREATETRANSFER_INSUFFICIENT_BALANCE =
      "ERROR_CREATETRANSFER_INSUFFICIENT_BALANCE";

  public static final String ERROR_CREATETRANSFER_CREDIT_DEBIT_EQUAL =
      "ERROR_CREATETRANSFER_CREDIT_DEBIT_EQUAL";

  /** WALLET */
  public static final String ERROR_CREATEWALLET_USER_ID_REQUIRED =
      "ERROR_CREATEWALLET_USER_ID_REQUIRED";

  public static final String ERROR_CREATEWALLET_USER_ID_INVALID =
      "ERROR_CREATEWALLET_USER_ID_INVALID";

  public static final String ERROR_CREATEWALLET_USER_ID_INEXISTENT_USER =
      "ERROR_CREATEWALLET_USER_ID_INEXISTENT_USER";

  public static final String ERROR_CREATEWALLET_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEWALLET_USER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEWALLET_DESCRIPTION_REQUIRED =
      "ERROR_CREATEWALLET_DESCRIPTION_REQUIRED";

  public static final String ERROR_CREATEWALLET_DESCRIPTION_INVALID =
      "ERROR_CREATEWALLET_DESCRIPTION_INVALID";

  public static final String ERROR_CREATEWALLET_CURRENCY_REQUIRED =
      "ERROR_CREATEWALLET_CURRENCY_REQUIRED";

  public static final String ERROR_CREATEWALLET_CURRENCY_INVALID =
      "ERROR_CREATEWALLET_CURRENCY_INVALID";

  public static final String ERROR_CREATEWALLET_TAG_MAXLENGTH = "ERROR_CREATEWALLET_TAG_MAXLENGTH";

  public static final String ERROR_CREATEWALLET_DUPLICATED_WALLET =
      "ERROR_CREATEWALLET_DUPLICATED_WALLET";

  public static final String ERROR_GETWALLET_INEXISTENT_WALLET =
      "ERROR_GETWALLET_INEXISTENT_WALLET";

  public static final String ERROR_GETWALLET_INVALID_WALLETID = "ERROR_GETWALLET_INVALID_WALLETID";

  /** BANK ACCOUNT */
  public static final String ERROR_CREATEBANKACCOUNT_TAG_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_TAG_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_USER_ID_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_USER_ID_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_USER_ID_INVALID =
      "ERROR_CREATEBANKACCOUNT_USER_ID_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_USER_ID_INEXISTENT =
      "ERROR_CREATEBANKACCOUNT_USER_ID_INEXISTENT";

  public static final String ERROR_CREATEBANKACCOUNT_OWNERNAME_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_OWNERNAME_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_OWNERNAME_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_OWNERNAME_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_OWNERADDRESS_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_OWNERADDRESS_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEBANKACCOUNT_USER_NOT_REGISTERED2PROVIDER";

  /** BANK ACCOUNT - IBAN GROUP */
  public static final String ERROR_CREATEBANKACCOUNT_IBAN_IBAN_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_IBAN_IBAN_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_IBAN_IBAN_INVALID =
      "ERROR_CREATEBANKACCOUNT_IBAN_IBAN_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_IBAN_BIC_MINLENGTH =
      "ERROR_CREATEBANKACCOUNT_IBAN_BIC_MINLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_IBAN_BIC_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_IBAN_BIC_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_IBAN_BIC_INVALID =
      "ERROR_CREATEBANKACCOUNT_IBAN_BIC_INVALID";

  /** BANK ACCOUNT - US GROUP */
  public static final String ERROR_CREATEBANKACCOUNT_US_ACCOUNTNUMBER_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_US_ACCOUNTNUMBER_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_US_ACCOUNTNUMBER_INVALID =
      "ERROR_CREATEBANKACCOUNT_US_ACCOUNTNUMBER_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_US_ACCOUNTNUMBER_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_US_ACCOUNTNUMBER_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_US_ABA_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_US_ABA_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_US_ABA_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_US_ABA_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_US_ABA_INVALID =
      "ERROR_CREATEBANKACCOUNT_US_ABA_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_US_DEPACCTYPE_INVALID =
      "ERROR_CREATEBANKACCOUNT_US_DEPACCTYPE_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_US_DEPACCTYPE_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_US_DEPACCTYPE_REQUIRED";

  /** BANK ACCOUNT - CA GROUP */
  public static final String ERROR_CREATEBANKACCOUNT_CA_BRANCHCODE_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_CA_BRANCHCODE_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_CA_BRANCHCODE_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_CA_BRANCHCODE_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_CA_BRANCHCODE_INVALID =
      "ERROR_CREATEBANKACCOUNT_CA_BRANCHCODE_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_CA_INSTNUMBER_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_CA_INSTNUMBER_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_CA_INSTNUMBER_MINLENGTH =
      "ERROR_CREATEBANKACCOUNT_CA_INSTNUMBER_MINLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_CA_INSTNUMBER_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_CA_INSTNUMBER_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_CA_INSTNUMBER_INVALID =
      "ERROR_CREATEBANKACCOUNT_CA_INSTNUMBER_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_CA_ACCOUNTNUMBER_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_CA_ACCOUNTNUMBER_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_CA_ACCOUNTNUMBER_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_CA_ACCOUNTNUMBER_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_CA_ACCOUNTNUMBER_INVALID =
      "ERROR_CREATEBANKACCOUNT_CA_ACCOUNTNUMBER_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_CA_BANKNAME_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_CA_BANKNAME_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_CA_BANKNAME_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_CA_BANKNAME_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_CA_BANKNAME_INVALID =
      "ERROR_CREATEBANKACCOUNT_CA_BANKNAME_INVALID";

  /** BANK ACCOUNT - GB GROUP */
  public static final String ERROR_CREATEBANKACCOUNT_GB_SORTCODE_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_GB_SORTCODE_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_GB_SORTCODE_MINLENGTH =
      "ERROR_CREATEBANKACCOUNT_GB_SORTCODE_MINLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_GB_SORTCODE_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_GB_SORTCODE_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_GB_SORTCODE_INVALID =
      "ERROR_CREATEBANKACCOUNT_GB_SORTCODE_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_GB_ACCOUNTNUMBER_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_GB_ACCOUNTNUMBER_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_GB_ACCOUNTNUMBER_MINLENGTH =
      "ERROR_CREATEBANKACCOUNT_GB_ACCOUNTNUMBER_MINLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_GB_ACCOUNTNUMBER_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_GB_ACCOUNTNUMBER_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_GB_ACCOUNTNUMBER_INVALID =
      "ERROR_CREATEBANKACCOUNT_GB_ACCOUNTNUMBER_INVALID";

  /** BANK ACCOUNT - OTHER GROUP */
  public static final String ERROR_CREATEBANKACCOUNT_OTHER_COUNTRY_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_OTHER_COUNTRY_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_OTHER_COUNTRY_INVALID =
      "ERROR_CREATEBANKACCOUNT_OTHER_COUNTRY_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_OTHER_BIC_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_OTHER_BIC_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_OTHER_BIC_MINLENGTH =
      "ERROR_CREATEBANKACCOUNT_OTHER_BIC_MINLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_OTHER_BIC_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_OTHER_BIC_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_OTHER_BIC_INVALID =
      "ERROR_CREATEBANKACCOUNT_OTHER_BIC_INVALID";

  public static final String ERROR_CREATEBANKACCOUNT_OTHER_ACCOUNTNUMBER_REQUIRED =
      "ERROR_CREATEBANKACCOUNT_OTHER_ACCOUNTNUMBER_REQUIRED";

  public static final String ERROR_CREATEBANKACCOUNT_OTHER_ACCOUNTNUMBER_MAXLENGTH =
      "ERROR_CREATEBANKACCOUNT_OTHER_ACCOUNTNUMBER_MAXLENGTH";

  public static final String ERROR_CREATEBANKACCOUNT_OTHER_ACCOUNTNUMBER_INVALID =
      "ERROR_CREATEBANKACCOUNT_OTHER_ACCOUNTNUMBER_INVALID";

  /** BANK ACCOUNT - GET */
  public static final String ERROR_GETBANKACCOUNT_INVALID_USERID =
      "ERROR_GETBANKACCOUNT_INVALID_USERID";

  public static final String ERROR_GETBANKACCOUNT_INVALID_BANKACCOUNTID =
      "ERROR_GETBANKACCOUNT_INVALID_BANKACCOUNTID";

  public static final String ERROR_GETBANKACCOUNT_INEXISTENT_USER =
      "ERROR_GETBANKACCOUNT_INEXISTENT_USER";

  public static final String ERROR_GETBANKACCOUNT_INEXISTENT_BANKACCOUNT =
      "ERROR_GETBANKACCOUNT_INEXISTENT_BANKACCOUNT";

  /** BANK ACCOUNT - DEACTIVATE */
  public static final String ERROR_DEACTIVATE_BANKACCOUNT_USERID_REQUIRED =
      "ERROR_DEACTIVATE_BANKACCOUNT_USERID_REQUIRED";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_INVALID_USERID =
      "ERROR_DEACTIVATE_BANKACCOUNT_INVALID_USERID";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_INEXISTENT_USER =
      "ERROR_DEACTIVATE_BANKACCOUNT_INEXISTENT_USER";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_DEACTIVATE_BANKACCOUNT_USER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_BANKACCOUNTID_REQUIRED =
      "ERROR_DEACTIVATE_BANKACCOUNT_BANKACCOUNTID_REQUIRED";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_INVALID_BANKACCOUNTID =
      "ERROR_DEACTIVATE_BANKACCOUNT_INVALID_BANKACCOUNTID";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_INEXISTENT_BANKACCOUNT =
      "ERROR_DEACTIVATE_BANKACCOUNT_INEXISTENT_BANKACCOUNT";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_OBJECT_NOT_REGISTERED2PROVIDER =
      "ERROR_DEACTIVATE_BANKACCOUNT_OBJECT_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_NEWSTATUS_REQUIRED =
      "ERROR_DEACTIVATE_BANKACCOUNT_NEWSTATUS_REQUIRED";

  public static final String ERROR_DEACTIVATE_BANKACCOUNT_NEWSTATUS_INVALID =
      "ERROR_DEACTIVATE_BANKACCOUNT_NEWSTATUS_INVALID";

  /** BANK ACCOUNT - GET BANK ACCOUNTS */
  public static final String ERROR_GETBANKACCOUNTS_INVALID_USERID =
      "ERROR_GETBANKACCOUNTS_INVALID_USERID";

  public static final String ERROR_GETBANKACCOUNTS_INEXISTENT_USER =
      "ERROR_GETBANKACCOUNTS_INEXISTENT_USER";

  /** WALLET TRANSACTIONS */
  public static final String ERROR_GETWALLETTRANSACTIONS_WALLETID_INVALID =
      "ERROR_GETWALLETTRANSACTIONS_WALLETID_INVALID";

  public static final String ERROR_GETWALLETTRANSACTIONS_INEXISTENT_WALLET =
      "ERROR_GETWALLETTRANSACTIONS_INEXISTENT_WALLET";

  /** WALLET LIST */
  public static final String ERROR_GETWALLETS_INVALID_USERID = "ERROR_GETWALLETS_INVALID_USERID";

  public static final String ERROR_GETWALLETS_INEXISTENT_USER = "ERROR_GETWALLETS_INEXISTENT_USER";

  /** TRANSACTION GET */
  public static final String ERROR_GETTRANSACTION_INVALID_TRANSACTIONID =
      "ERROR_GETTRANSACTION_INVALID_TRANSACTIONID";

  public static final String ERROR_GETTRANSACTION_INEXISTENT_TRANSACTION =
      "ERROR_GETTRANSACTION_INEXISTENT_TRANSACTION";

  public static final String ERROR_GETTRANSACTION_INVALID_TYPE =
      "ERROR_GETTRANSACTION_INVALID_TYPE";

  public static final String ERROR_GETTRANSACTION_INEXISTENT_PAYOUT =
      "ERROR_GETTRANSACTION_INEXISTENT_PAYOUT";

  public static final String ERROR_GETTRANSACTION_INEXISTENT_PAYIN =
      "ERROR_GETTRANSACTION_INEXISTENT_PAYIN";

  /** TRANSACTION REFUND */
  public static final String ERROR_REFUNDTRANSACTION_TRANSACTIONID_REQUIRED =
      "ERROR_REFUNDTRANSACTION_TRANSACTIONID_REQUIRED";

  public static final String ERROR_REFUNDTRANSACTION_TRANSACTIONID_INVALID =
      "ERROR_REFUNDTRANSACTION_TRANSACTIONID_INVALID";

  public static final String ERROR_REFUNDTRANSACTION_TRANSACTION_INEXISTENT =
      "ERROR_REFUNDTRANSACTION_TRANSACTION_INEXISTENT";

  public static final String ERROR_REFUNDTRANSACTION_INVALID_TYPE =
      "ERROR_REFUNDTRANSACTION_INVALID_TYPE";

  public static final String ERROR_REFUNDTRANSACTION_DEBITWALLET_INEXISTENT =
      "ERROR_REFUNDTRANSACTION_DEBITWALLET_INEXISTENT";

  public static final String ERROR_REFUNDTRANSACTION_DEBITUSER_INEXISTENT =
      "ERROR_REFUNDTRANSACTION_DEBITUSER_INEXISTENT";

  public static final String ERROR_REFUNDTRANSACTION_CREDITWALLET_INEXISTENT =
      "ERROR_REFUNDTRANSACTION_CREDITWALLET_INEXISTENT";

  public static final String ERROR_REFUNDTRANSACTION_CREDITUSER_INEXISTENT =
      "ERROR_REFUNDTRANSACTION_CREDITUSER_INEXISTENT";

  public static final String ERROR_REFUNDTRANSACTION_ORIGINALTRANSACTION_NOT_SUCCEEDED =
      "ERROR_REFUNDTRANSACTION_ORIGINALTRANSACTION_NOT_SUCCEEDED";

  public static final String ERROR_REFUNDTRANSACTION_ORIGINALTRANSACTION_NOT_REGISTERED2PROVIDER =
      "ERROR_REFUNDTRANSACTION_ORIGINALTRANSACTION_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_REFUNDTRANSACTION_ALREADY_REFUNDED =
      "ERROR_REFUNDTRANSACTION_ALREADY_REFUNDED";

  public static final String ERROR_REFUNDTRANSACTION_INSUFFICIENT_BALANCE =
      "ERROR_REFUNDTRANSACTION_INSUFFICIENT_BALANCE";

  public static final String ERROR_REFUNDTRANSACTION_TAG_MAXLENGTH =
      "ERROR_REFUNDTRANSACTION_TAG_MAXLENGTH";

  /** DOCUMENT CREATE */
  public static final String ERROR_CREATEDOCUMENT_USERID_REQUIRED =
      "ERROR_CREATEDOCUMENT_USERID_REQUIRED";

  public static final String ERROR_CREATEDOCUMENT_USERID_INVALID =
      "ERROR_CREATEDOCUMENT_USERID_INVALID";

  public static final String ERROR_CREATEDOCUMENT_USERID_INEXISTENT =
      "ERROR_CREATEDOCUMENT_USERID_INEXISTENT";

  public static final String ERROR_CREATEDOCUMENT_TAG_MAXLENGTH =
      "ERROR_CREATEDOCUMENT_TAG_MAXLENGTH";

  public static final String ERROR_CREATEDOCUMENT_TYPE_REQUIRED =
      "ERROR_CREATEDOCUMENT_TYPE_REQUIRED";

  public static final String ERROR_CREATEDOCUMENT_TYPE_INVALID =
      "ERROR_CREATEDOCUMENT_TYPE_INVALID";

  public static final String ERROR_CREATEDOCUMENT_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEDOCUMENT_USER_NOT_REGISTERED2PROVIDER";

  /** DOCUMENT CREATE PAGE */
  public static final String ERROR_CREATEDOCUMENTPAGE_USERID_REQUIRED =
      "ERROR_CREATEDOCUMENTPAGE_USERID_REQUIRED";

  public static final String ERROR_CREATEDOCUMENTPAGE_USERID_INVALID =
      "ERROR_CREATEDOCUMENTPAGE_USERID_INVALID";

  public static final String ERROR_CREATEDOCUMENTPAGE_USERID_INEXISTENT =
      "ERROR_CREATEDOCUMENTPAGE_USERID_INEXISTENT";

  public static final String ERROR_CREATEDOCUMENTPAGE_DOCID_REQUIRED =
      "ERROR_CREATEDOCUMENTPAGE_DOCID_REQUIRED";

  public static final String ERROR_CREATEDOCUMENTPAGE_DOCID_INVALID =
      "ERROR_CREATEDOCUMENTPAGE_DOCID_INVALID";

  public static final String ERROR_CREATEDOCUMENTPAGE_DOCID_INEXISTENT =
      "ERROR_CREATEDOCUMENTPAGE_DOCID_INEXISTENT";

  public static final String ERROR_CREATEDOCUMENTPAGE_FILE_REQUIRED =
      "ERROR_CREATEDOCUMENTPAGE_FILE_REQUIRED";

  public static final String ERROR_CREATEDOCUMENTPAGE_FILE_MINLENGTH =
      "ERROR_CREATEDOCUMENTPAGE_FILE_MINLENGTH";

  public static final String ERROR_CREATEDOCUMENTPAGE_FILE_INVALIDB64 =
      "ERROR_CREATEDOCUMENTPAGE_FILE_INVALIDB64";

  public static final String ERROR_CREATEDOCUMENTPAGE_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEDOCUMENTPAGE_USER_NOT_REGISTERED2PROVIDER";

  /** DOCUMENT GET */
  public static final String ERROR_GETDOCUMENT_INVALID_DOCID = "ERROR_GETDOCUMENT_INVALID_DOCID";

  public static final String ERROR_GETDOCUMENT_INEXISTENT_DOCUMENT =
      "ERROR_GETDOCUMENT_INEXISTENT_DOCUMENT";

  /** GET USER DOCUMENTS */
  public static final String ERROR_GETDOCUMENTS_INVALID_USERID =
      "ERROR_GETDOCUMENTS_INVALID_USERID";

  public static final String ERROR_GETDOCUMENTS_INEXISTENT_USER =
      "ERROR_GETDOCUMENTS_INEXISTENT_USER";

  /** DOCUMENT SUBMIT */
  public static final String ERROR_SUBMITDOCUMENT_DOCID_REQUIRED =
      "ERROR_SUBMITDOCUMENT_DOCID_REQUIRED";

  public static final String ERROR_SUBMITDOCUMENT_DOCID_INVALID =
      "ERROR_SUBMITDOCUMENT_DOCID_INVALID";

  public static final String ERROR_SUBMITDOCUMENT_DOCID_INEXISTENT =
      "ERROR_SUBMITDOCUMENT_DOCID_INEXISTENT";

  public static final String ERROR_SUBMITDOCUMENT_INVALID_STATUS =
      "ERROR_SUBMITDOCUMENT_INVALID_STATUS";

  public static final String ERROR_SUBMITDOCUMENT_DOCUMENT_NOT_REGISTERED2PROVIDER =
      "ERROR_SUBMITDOCUMENT_DOCUMENT_NOT_REGISTERED2PROVIDER";

  /** UBO DECLARATION GET */
  public static final String ERROR_GETUBODECLARATION_INVALID_DECLARATIONID =
      "ERROR_GETUBODECLARATION_INVALID_DECLARATIONID";

  public static final String ERROR_GETUBODECLARATION_INEXISTENT_DECLARATION =
      "ERROR_GETUBODECLARATION_INEXISTENT_DECLARATION";

  /** CREATE UBO DECLARATION */
  public static final String ERROR_CREATEUBODECLARATION_USERID_REQUIRED =
      "ERROR_CREATEUBODECLARATION_USERID_REQUIRED";

  public static final String ERROR_CREATEUBODECLARATION_USERID_INVALID =
      "ERROR_CREATEUBODECLARATION_USERID_INVALID";

  public static final String ERROR_CREATEUBODECLARATION_USERID_INEXISTENT =
      "ERROR_CREATEUBODECLARATION_USERID_INEXISTENT";

  public static final String ERROR_CREATEUBODECLARATION_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEUBODECLARATION_USER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEUBODECLARATION_IN_PROGRESS =
      "ERROR_CREATEUBODECLARATION_IN_PROGRESS";

  public static final String ERROR_CREATEUBODECLARATION_INVALID_OPERATION =
      "ERROR_CREATEUBODECLARATION_INVALID_OPERATION";

  /** SUBMIT UBO DECLARATION */
  public static final String ERROR_SUBMITUBODECLARATION_USERID_REQUIRED =
      "ERROR_SUBMITUBODECLARATION_USERID_REQUIRED";

  public static final String ERROR_SUBMITUBODECLARATION_USERID_INVALID =
      "ERROR_SUBMITUBODECLARATION_USERID_INVALID";

  public static final String ERROR_SUBMITUBODECLARATION_USERID_INEXISTENT =
      "ERROR_SUBMITUBODECLARATION_USERID_INEXISTENT";

  public static final String ERROR_SUBMITUBODECLARATION_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_SUBMITUBODECLARATION_USER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_SUBMITUBODECLARATION_DOCID_REQUIRED =
      "ERROR_SUBMITUBODECLARATION_DOCID_REQUIRED";

  public static final String ERROR_SUBMITUBODECLARATION_DOCID_INVALID =
      "ERROR_SUBMITUBODECLARATION_DOCID_INVALID";

  public static final String ERROR_SUBMITUBODECLARATION_DOCID_INEXISTENT =
      "ERROR_SUBMITUBODECLARATION_DOCID_INEXISTENT";

  public static final String ERROR_SUBMITUBODECLARATION_INVALID_STATUS =
      "ERROR_SUBMITUBODECLARATION_INVALID_STATUS";

  public static final String ERROR_SUBMITUBODECLARATION_DOCUMENT_NOT_REGISTERED2PROVIDER =
      "ERROR_SUBMITUBODECLARATION_DOCUMENT_NOT_REGISTERED2PROVIDER";

  /** CREATE UBO */
  public static final String ERROR_CREATEUBO_USERID_REQUIRED = "ERROR_CREATEUBO_USERID_REQUIRED";

  public static final String ERROR_CREATEUBO_USERID_INVALID = "ERROR_CREATEUBO_USERID_INVALID";

  public static final String ERROR_CREATEUBO_USERID_INEXISTENT =
      "ERROR_CREATEUBO_USERID_INEXISTENT";

  public static final String ERROR_CREATEUBO_DOCID_REQUIRED = "ERROR_CREATEUBO_DOCID_REQUIRED";

  public static final String ERROR_CREATEUBO_DOCID_INVALID = "ERROR_CREATEUBO_DOCID_INVALID";

  public static final String ERROR_CREATEUBO_DOCID_INEXISTENT = "ERROR_CREATEUBO_DOCID_INEXISTENT";

  public static final String ERROR_CREATEUBO_FNAME_REQUIRED = "ERROR_CREATEUBO_FNAME_REQUIRED";

  public static final String ERROR_CREATEUBO_FNAME_MAXLENGTH = "ERROR_CREATEUBO_FNAME_MAXLENGTH";

  public static final String ERROR_CREATEUBO_LNAME_REQUIRED = "ERROR_CREATEUBO_LNAME_REQUIRED";

  public static final String ERROR_CREATEUBO_BDATE_REQUIRED = "ERROR_CREATEUBO_BDATE_REQUIRED";

  public static final String ERROR_CREATEUBO_BDATE_INVALID = "ERROR_CREATEUBO_BDATE_INVALID";

  public static final String ERROR_CREATEUBO_LNAME_MAXLENGTH = "ERROR_CREATEUBO_LNAME_MAXLENGTH";

  public static final String ERROR_CREATEUBO_NATIONALITY_REQUIRED =
      "ERROR_CREATEUBO_NATIONALITY_REQUIRED";

  public static final String ERROR_CREATEUBO_NATIONALITY_MAXLENGTH =
      "ERROR_CREATEUBO_NATIONALITY_MAXLENGTH";

  public static final String ERROR_CREATEUBO_NATIONALITY_INVALID =
      "ERROR_CREATEUBO_NATIONALITY_INVALID";

  public static final String ERROR_CREATEUBO_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEUBO_USER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEUBO_INVALID_STATUS = "ERROR_CREATEUBO_INVALID_STATUS";

  public static final String ERROR_CREATEUBO_DOCUMENT_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEUBO_DOCUMENT_NOT_REGISTERED2PROVIDER";

  /** UPDATE UBO */
  public static final String ERROR_UPDATEUBO_UBOID_INVALID = "ERROR_UPDATEUBO_UBOID_INVALID";

  /** CREATE PAY OUT */
  public static final String ERROR_CREATEPAYOUT_DEBITWALLETID_REQUIRED =
      "ERROR_CREATEPAYOUT_DEBITWALLETID_REQUIRED";

  public static final String ERROR_CREATEPAYOUT_DEBITWALLETID_INVALID =
      "ERROR_CREATEPAYOUT_DEBITWALLETID_INVALID";

  public static final String ERROR_CREATEPAYOUT_DEBITFUNDS_REQUIRED =
      "ERROR_CREATEPAYOUT_DEBITFUNDS_REQUIRED";

  public static final String ERROR_CREATEPAYOUT_FEES_REQUIRED = "ERROR_CREATEPAYOUT_FEES_REQUIRED";

  public static final String ERROR_CREATEPAYOUT_FEEMODEL_REQUIRED =
      "ERROR_CREATEPAYOUT_FEEMODEL_REQUIRED";

  public static final String ERROR_CREATEPAYOUT_FEEMODEL_INVALID =
      "ERROR_CREATEPAYOUT_FEEMODEL_INVALID";

  public static final String ERROR_CREATEPAYOUT_BANKACCOUNTID_REQUIRED =
      "ERROR_CREATEPAYOUT_BANKACCOUNTID_REQUIRED";

  public static final String ERROR_CREATEPAYOUT_BANKACCOUNTID_INVALID =
      "ERROR_CREATEPAYOUT_BANKACCOUNTID_INVALID";

  public static final String ERROR_CREATEPAYOUT_WIREREF_MAXLENGTH =
      "ERROR_CREATEPAYOUT_WIREREF_MAXLENGTH";

  public static final String ERROR_CREATEPAYOUT_TAG_MAXLENGTH = "ERROR_CREATEPAYOUT_TAG_MAXLENGTH";

  public static final String ERROR_CREATEPAYOUT_REQUEST_CURRENCY_MISSMATCH =
      "ERROR_CREATEPAYOUT_REQUEST_CURRENCY_MISSMATCH";

  public static final String ERROR_CREATEPAYOUT_REQUEST_AMOUNT_SMALLER_THAN_FEE =
      "ERROR_CREATEPAYOUT_REQUEST_AMOUNT_SMALLER_THAN_FEE";

  public static final String ERROR_CREATEPAYOUT_DEBITWALLET_INEXISTENT =
      "ERROR_CREATEPAYOUT_DEBITWALLET_INEXISTENT";

  public static final String ERROR_CREATEPAYOUT_DEBITWALLET_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEPAYOUT_DEBITWALLET_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEPAYOUT_DEBITUSER_INEXISTENT =
      "ERROR_CREATEPAYOUT_DEBITUSER_INEXISTENT";

  public static final String ERROR_CREATEPAYOUT_DEBITUSER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEPAYOUT_DEBITUSER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEPAYOUT_REQUEST_CURRENCY_INVALID =
      "ERROR_CREATEPAYOUT_REQUEST_CURRENCY_INVALID";

  public static final String ERROR_CREATEPAYOUT_INSUFFICIENT_BALANCE =
      "ERROR_CREATEPAYOUT_INSUFFICIENT_BALANCE";

  public static final String ERROR_CREATEPAYOUT_INEXISTENT_BANKACCOUNT =
      "ERROR_CREATEPAYOUT_INEXISTENT_BANKACCOUNT";

  /** CREATE PAY IN */
  public static final String ERROR_CREATEPAYIN_CREDITWALLETID_REQUIRED =
      "ERROR_CREATEPAYIN_CREDITWALLETID_REQUIRED";

  public static final String ERROR_CREATEPAYIN_CREDITWALLETID_INVALID =
      "ERROR_CREATEPAYIN_CREDITWALLETID_INVALID";

  public static final String ERROR_CREATEPAYIN_DEBITFUNDS_REQUIRED =
      "ERROR_CREATEPAYIN_DEBITFUNDS_REQUIRED";

  public static final String ERROR_CREATEPAYIN_FEES_REQUIRED = "ERROR_CREATEPAYIN_FEES_REQUIRED";

  public static final String ERROR_CREATEPAYIN_FEEMODEL_REQUIRED =
      "ERROR_CREATEPAYIN_FEEMODEL_REQUIRED";

  public static final String ERROR_CREATEPAYIN_FEEMODEL_INVALID =
      "ERROR_CREATEPAYIN_FEEMODEL_INVALID";

  public static final String ERROR_CREATEPAYIN_TAG_MAXLENGTH = "ERROR_CREATEPAYIN_TAG_MAXLENGTH";

  public static final String ERROR_CREATEPAYIN_RETURNURL_REQUIRED =
      "ERROR_CREATEPAYIN_RETURNURL_REQUIRED";

  public static final String ERROR_CREATEPAYIN_RETURNURL_MAXLENGTH =
      "ERROR_CREATEPAYIN_RETURNURL_MAXLENGTH";

  public static final String ERROR_CREATEPAYIN_RETURNURL_INVALID =
      "ERROR_CREATEPAYIN_RETURNURL_INVALID";

  public static final String ERROR_CREATEPAYIN_CARDTYPE_REQUIRED =
      "ERROR_CREATEPAYIN_CARDTYPE_REQUIRED";

  public static final String ERROR_CREATEPAYIN_CARDTYPE_INVALID =
      "ERROR_CREATEPAYIN_CARDTYPE_INVALID";

  public static final String ERROR_CREATEPAYIN_SECUREMODE_REQUIRED =
      "ERROR_CREATEPAYIN_SECUREMODE_REQUIRED";

  public static final String ERROR_CREATEPAYIN_SECUREMODE_INVALID =
      "ERROR_CREATEPAYIN_SECUREMODE_INVALID";

  public static final String ERROR_CREATEPAYIN_CULTURE_REQUIRED =
      "ERROR_CREATEPAYIN_CULTURE_REQUIRED";

  public static final String ERROR_CREATEPAYIN_CULTURE_INVALID =
      "ERROR_CREATEPAYIN_CULTURE_INVALID";

  public static final String ERROR_CREATEPAYIN_TEMPLATEURL_INVALID =
      "ERROR_CREATEPAYIN_TEMPLATEURL_INVALID";

  public static final String ERROR_CREATEPAYIN_TEMPLATEURL_MAXLENGTH =
      "ERROR_CREATEPAYIN_TEMPLATEURL_MAXLENGTH";

  public static final String ERROR_CREATEPAYIN_STATEMENTDESC_INVALID =
      "ERROR_CREATEPAYIN_STATEMENTDESC_INVALID";

  public static final String ERROR_CREATEPAYIN_STATEMENTDESC_MAXLENGTH =
      "ERROR_CREATEPAYIN_STATEMENTDESC_MAXLENGTH";

  public static final String ERROR_CREATEPAYIN_REQUEST_CURRENCY_MISSMATCH =
      "ERROR_CREATEPAYIN_REQUEST_CURRENCY_MISSMATCH";

  public static final String ERROR_CREATEPAYIN_REQUEST_AMOUNT_SMALLER_THAN_FEE =
      "ERROR_CREATEPAYIN_REQUEST_AMOUNT_SMALLER_THAN_FEE";

  public static final String ERROR_CREATEPAYIN_CREDITWALLET_INEXISTENT =
      "ERROR_CREATEPAYIN_CREDITWALLET_INEXISTENT";

  public static final String ERROR_CREATEPAYIN_CREDITWALLET_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEPAYIN_CREDITWALLET_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEPAYIN_CREDITUSER_INEXISTENT =
      "ERROR_CREATEPAYIN_CREDITUSER_INEXISTENT";

  public static final String ERROR_CREATEPAYIN_CREDITUSER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEPAYIN_CREDITUSER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEPAYIN_REQUEST_CURRENCY_INVALID =
      "ERROR_CREATEPAYIN_REQUEST_CURRENCY_INVALID";

  /** CARDS CREATE */
  public static final String ERROR_CREATEBANKCARD_USERID_REQUIRED =
      "ERROR_CREATEBANKCARD_USERID_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_USERID_INVALID =
      "ERROR_CREATEBANKCARD_USERID_INVALID";

  public static final String ERROR_CREATEBANKCARD_USERID_INEXISTENT =
      "ERROR_CREATEBANKCARD_USERID_INEXISTENT";

  public static final String ERROR_CREATEBANKCARD_TYPE_REQUIRED =
      "ERROR_CREATEBANKCARD_TYPE_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_TYPE_INVALID =
      "ERROR_CREATEBANKCARD_TYPE_INVALID";

  public static final String ERROR_CREATEBANKCARD_TAG_MAXLENGTH =
      "ERROR_CREATEBANKCARD_TAG_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_INVALID_USER_TYPE =
      "ERROR_CREATEBANKCARD_INVALID_USER_TYPE";

  public static final String ERROR_CREATEBANKCARD_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEBANKCARD_USER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEBANKCARD_USER_MISSING_ADDRESS =
      "ERROR_CREATEBANKCARD_USER_MISSING_ADDRESS";

  public static final String ERROR_CREATEBANKCARD_EMBOSSNAME_REQUIRED =
      "ERROR_CREATEBANKCARD_EMBOSSNAME_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_EMBOSSNAME_INVALID =
      "ERROR_CREATEBANKCARD_EMBOSSNAME_INVALID";

  public static final String ERROR_CREATEBANKCARD_FIRSTNAME_REQUIRED =
      "ERROR_CREATEBANKCARD_FIRSTNAME_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_FIRSTNAME_MAXLENGTH =
      "ERROR_CREATEBANKCARD_FIRSTNAME_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_LASTNAME_REQUIRED =
      "ERROR_CREATEBANKCARD_LASTNAME_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_LASTNAME_MAXLENGTH =
      "ERROR_CREATEBANKCARD_LASTNAME_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_LINE1_REQUIRED =
      "ERROR_CREATEBANKCARD_ADDRESS_LINE1_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_LINE1_MAXLENGTH =
      "ERROR_CREATEBANKCARD_ADDRESS_LINE1_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_LINE2_MAXLENGTH =
      "ERROR_CREATEBANKCARD_ADDRESS_LINE2_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_LINE3_MAXLENGTH =
      "ERROR_CREATEBANKCARD_ADDRESS_LINE3_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_LINE4_MAXLENGTH =
      "ERROR_CREATEBANKCARD_ADDRESS_LINE3_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_CITY_REQUIRED =
      "ERROR_CREATEBANKCARD_ADDRESS_CITY_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_CITY_MAXLENGTH =
      "ERROR_CREATEBANKCARD_ADDRESS_CITY_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_COUNTY_MAXLENGTH =
      "ERROR_CREATEBANKCARD_ADDRESS_COUNTY_MAXLENGTH";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_COUNTRY_REQUIRED =
      "ERROR_CREATEBANKCARD_ADDRESS_COUNTRY_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_COUNTRY_INVALID =
      "ERROR_CREATEBANKCARD_ADDRESS_COUNTRY_INVALID";
  public static final String ERROR_CARDUSERINFO_REQUIRED = "ERROR_CARDUSERINFO_REQUIRED";

  public static final String ERROR_CARDUSERINFO_EMPLOYMENTSTATUS_REQUIRED =
      "ERROR_CARDUSERINFO_EMPLOYMENTSTATUS_REQUIRED";

  public static final String ERROR_CARDUSERINFO_EMPLOYMENTSTATUS_INVALID =
      "ERROR_CARDUSERINFO_EMPLOYMENTSTATUS_INVALID";

  public static final String ERROR_CARDUSERINFO_OCCUPATION_REQUIRED =
      "ERROR_CARDUSERINFO_OCCUPATION_REQUIRED";

  public static final String ERROR_CARDUSERINFO_OCCUPATION_INVALID =
      "ERROR_CARDUSERINFO_OCCUPATION_INVALID";

  public static final String ERROR_CARDUSERINFO_PURPOSE_REQUIRED =
      "ERROR_CARDUSERINFO_PURPOSE_REQUIRED";

  public static final String ERROR_CARDUSERINFO_PURPOSE_INVALID =
      "ERROR_CARDUSERINFO_PURPOSE_INVALID";

  public static final String ERROR_CARDUSERINFO_MONTHLYINCOME_REQUIRED =
      "ERROR_CARDUSERINFO_MONTHLYINCOME_REQUIRED";

  public static final String ERROR_CARDUSERINFO_MONTHLYINCOME_INVALID =
      "ERROR_CARDUSERINFO_MONTHLYINCOME_INVALID";

  public static final String ERROR_CARDUSERINFO_ESTATE_REQUIRED =
      "ERROR_CARDUSERINFO_ESTATE_REQUIRED";

  public static final String ERROR_CARDUSERINFO_ESTATE_INVALID =
      "ERROR_CARDUSERINFO_ESTATE_INVALID";

  /** CARDS GET */
  public static final String ERROR_CREATEBANKCARD_ADDRESS_POSTALCODE_REQUIRED =
      "ERROR_CREATEBANKCARD_ADDRESS_POSTALCODE_REQUIRED";

  public static final String ERROR_CREATEBANKCARD_ADDRESS_POSTALCODE_MAXLENGTH =
      "ERROR_CREATEBANKCARD_ADDRESS_POSTALCODE_MAXLENGTH";

  /** CARDS GET */
  public static final String ERROR_GETCARD_INVALID_CARDID = "ERROR_GETCARD_INVALID_CARDID";

  public static final String ERROR_GETCARD_INEXISTENT_CARD = "ERROR_GETCARD_INEXISTENT_CARD";

  public static final String ERROR_GETCARD_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_GETCARD_CARD_NOT_REGISTERED2PROVIDER";

  /** CARDS RETRIEVE MANUALLY REISSUED CARD */
  public static final String ERROR_RETRIEVE_MAN_REISSUED_CARD_INVALID_PROVIDERID =
      "ERROR_RETRIEVE_MAN_REISSUED_CARD_INVALID_PROVIDERID";

  public static final String ERROR_RETRIEVE_MAN_REISSUED_CARD_INEXISTENT_CARD_AT_PROVIDER =
      "ERROR_RETRIEVE_MAN_REISSUED_CARD_INEXISTENT_CARD_AT_PROVIDER";

  public static final String ERROR_RETRIEVE_MAN_REISSUED_CARD_ALREADY_RETRIEVED =
      "ERROR_RETRIEVE_MAN_REISSUED_CARD_ALREADY_RETRIEVED";
  public static final String ERROR_RETRIEVE_MAN_REISSUED_CARD_NOT_SAME_PERSON =
      "ERROR_RETRIEVE_MAN_REISSUED_CARD_NOT_SAME_PERSON";

  /** CARDS UPGRADE */
  public static final String ERROR_UPGRADEBANKCARD_CARDID_REQUIRED =
      "ERROR_UPGRADEBANKCARD_CARDID_REQUIRED";

  public static final String ERROR_UPGRADEBANKCARD_CARDID_INVALID =
      "ERROR_UPGRADEBANKCARD_CARDID_INVALID";

  public static final String ERROR_UPGRADEBANKCARD_INEXISTENT_CARD =
      "ERROR_UPGRADEBANKCARD_INEXISTENT_CARD";

  public static final String ERROR_UPGRADEBANKCARD_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_UPGRADEBANKCARD_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_UPGRADEBANKCARD_CARD_NOT_VIRTUAL =
      "ERROR_UPGRADEBANKCARD_CARD_NOT_VIRTUAL";

  public static final String ERROR_UPGRADEBANKCARD_CARD_INVALID_STATUS =
      "ERROR_UPGRADEBANKCARD_CARD_INVALID_STATUS";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_LINE1_REQUIRED =
      "ERROR_UPGRADEBANKCARD_ADDRESS_LINE1_REQUIRED";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_LINE1_MAXLENGTH =
      "ERROR_UPGRADEBANKCARD_ADDRESS_LINE1_MAXLENGTH";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_LINE2_MAXLENGTH =
      "ERROR_UPGRADEBANKCARD_ADDRESS_LINE2_MAXLENGTH";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_LINE3_MAXLENGTH =
      "ERROR_UPGRADEBANKCARD_ADDRESS_LINE3_MAXLENGTH";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_LINE4_MAXLENGTH =
      "ERROR_UPGRADEBANKCARD_ADDRESS_LINE3_MAXLENGTH";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_CITY_REQUIRED =
      "ERROR_UPGRADEBANKCARD_ADDRESS_CITY_REQUIRED";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_CITY_MAXLENGTH =
      "ERROR_UPGRADEBANKCARD_ADDRESS_CITY_MAXLENGTH";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_COUNTY_REQUIRED =
      "ERROR_UPGRADEBANKCARD_ADDRESS_COUNTY_REQUIRED";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_COUNTY_MAXLENGTH =
      "ERROR_UPGRADEBANKCARD_ADDRESS_COUNTY_MAXLENGTH";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_COUNTRY_REQUIRED =
      "ERROR_UPGRADEBANKCARD_ADDRESS_COUNTRY_REQUIRED";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_COUNTRY_INVALID =
      "ERROR_UPGRADEBANKCARD_ADDRESS_COUNTRY_INVALID";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_POSTALCODE_REQUIRED =
      "ERROR_CREATEBANKCARD_ADDRESS_POSTALCODE_REQUIRED";

  public static final String ERROR_UPGRADEBANKCARD_ADDRESS_POSTALCODE_MAXLENGTH =
      "ERROR_UPGRADEBANKCARD_ADDRESS_POSTALCODE_MAXLENGTH";

  /** CARDS CHANGE STATUS */
  public static final String ERROR_CHANGECARDSTATUS_CARDID_REQUIRED =
      "ERROR_CHANGECARDSTATUS_CARDID_REQUIRED";

  public static final String ERROR_CHANGECARDSTATUS_CARDID_INVALID =
      "ERROR_CHANGECARDSTATUS_CARDID_INVALID";

  public static final String ERROR_CHANGECARDSTATUS_OLDSTATUS_REQUIRED =
      "ERROR_CHANGECARDSTATUS_OLDSTATUS_REQUIRED";

  public static final String ERROR_CHANGECARDSTATUS_OLDSTATUS_INVALID =
      "ERROR_CHANGECARDSTATUS_OLDSTATUS_INVALID";

  public static final String ERROR_CHANGECARDSTATUS_NEWSTATUS_REQUIRED =
      "ERROR_CHANGECARDSTATUS_NEWSTATUS_REQUIRED";

  public static final String ERROR_CHANGECARDSTATUS_NEWSTATUS_INVALID =
      "ERROR_CHANGECARDSTATUS_NEWSTATUS_INVALID";

  public static final String ERROR_CHANGECARDSTATUS_INEXISTENT_CARD =
      "ERROR_CHANGECARDSTATUS_INEXISTENT_CARD";

  public static final String ERROR_CHANGECARDSTATUS_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_CHANGECARDSTATUS_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CHANGECARDSTATUS_CARD_STATUS_MISSMATCH =
      "ERROR_CHANGECARDSTATUS_CARD_STATUS_MISSMATCH";

  /** ADD CARD CURRENCY */
  public static final String ERROR_ADDCARDCURRENCY_CARDID_REQUIRED =
      "ERROR_ADDCARDCURRENCY_CARDID_REQUIRED";

  public static final String ERROR_ADDCARDCURRENCY_CARDID_INVALID =
      "ERROR_ADDCARDCURRENCY_CARDID_INVALID";

  public static final String ERROR_ADDCARDCURRENCY_CURRENCY_REQUIRED =
      "ERROR_ADDCARDCURRENCY_CURRENCY_REQUIRED";

  public static final String ERROR_ADDCARDCURRENCY_CURRENCY_INVALID =
      "ERROR_ADDCARDCURRENCY_CURRENCY_INVALID";

  public static final String ERROR_ADDCARDCURRENCY_INEXISTENT_CARD =
      "ERROR_ADDCARDCURRENCY_INEXISTENT_CARD";

  public static final String ERROR_ADDCARDCURRENCY_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_ADDCARDCURRENCY_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_ADDCARDCURRENCY_DUPLICATED_CURRENCY =
      "ERROR_ADDCARDCURRENCY_DUPLICATED_CURRENCY";

  public static final String ERROR_ADDCARDCURRENCY_CURRENCY_NOT_ALLOWED =
      "ERROR_ADDCARDCURRENCY_CURRENCY_NOT_ALLOWED";

  /** GET CARD WALLET */
  public static final String ERROR_GETCARDWALLET_INVALID_CARDID =
      "ERROR_GETCARDWALLET_INVALID_CARDID";

  public static final String ERROR_GETCARDWALLET_INEXISTENT_CARD =
      "ERROR_GETCARDWALLET_INEXISTENT_CARD";

  public static final String ERROR_GETCARDWALLET_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_GETCARDWALLET_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_GETCARDWALLET_INEXISTENT_CARDWALLET =
      "ERROR_GETCARDWALLET_INEXISTENT_CARDWALLET";

  public static final String ERROR_GETCARDWALLET_INVALID_CURRENCY =
      "ERROR_GETCARDWALLET_INVALID_CURRENCY";

  public static final String ERROR_GETCARDWALLET_CURRENCY_NOT_ALLOWED =
      "ERROR_GETCARDWALLET_CURRENCY_NOT_ALLOWED";

  /** GET CARD WALLET TRANSACTIONS */
  public static final String ERROR_GETCARDWALLETTRANS_INVALID_CARDID =
      "ERROR_GETCARDWALLETTRANS_INVALID_CARDID";

  public static final String ERROR_GETCARDWALLETTRANS_INEXISTENT_CARD =
      "ERROR_GETCARDWALLETTRANS_INEXISTENT_CARD";

  public static final String ERROR_GETCARDWALLETTRANS_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_GETCARDWALLETTRANS_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_GETCARDWALLETTRANS_INEXISTENT_CARDWALLET =
      "ERROR_GETCARDWALLETTRANS_INEXISTENT_CARDWALLET";

  public static final String ERROR_GETCARDWALLETTRANS_INVALID_CURRENCY =
      "ERROR_GETCARDWALLETTRANS_INVALID_CURRENCY";

  public static final String ERROR_GETCARDWALLETTRANS_CURRENCY_NOT_ALLOWED =
      "ERROR_GETCARDWALLETTRANS_CURRENCY_NOT_ALLOWED";

  public static final String ERROR_GETCARDWALLETTRANS_INVALID_STARTDATE =
      "ERROR_GETCARDWALLETTRANS_INVALID_STARTDATE";

  public static final String ERROR_GETCARDWALLETTRANS_INVALID_ENDDATE =
      "ERROR_GETCARDWALLETTRANS_INVALID_ENDDATE";

  public static final String ERROR_GETCARDWALLETTRANS_INVALID_PERIOD =
      "ERROR_GETCARDWALLETTRANS_INVALID_PERIOD";

  /** GET CARD NUMBER */
  public static final String ERROR_GETCARDNO_INVALID_CARDID = "ERROR_GETCARDNO_INVALID_CARDID";

  public static final String ERROR_GETCARDNO_INEXISTENT_CARD = "ERROR_GETCARDNO_INEXISTENT_CARD";

  public static final String ERROR_GETCARDNO_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_GETCARDNO_CARD_NOT_REGISTERED2PROVIDER";

  /** GET CARD NUMBER LOCAL */
  public static final String ERROR_GETCARDNOLOCAL_INVALID_CARDID =
      "ERROR_GETCARDNOLOCAL_INVALID_CARDID";

  public static final String ERROR_GETCARDNOLOCAL_INEXISTENT_CARD =
      "ERROR_GETCARDNOLOCAL_INEXISTENT_CARD";

  public static final String ERROR_GETCARDNOLOCAL_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_GETCARDNOLOCAL_CARD_NOT_REGISTERED2PROVIDER";

  /** GET CARD EXPIRY DATE */
  public static final String ERROR_GETCARDEXPDATE_INVALID_CARDID =
      "ERROR_GETCARDEXPDATE_INVALID_CARDID";

  public static final String ERROR_GETCARDEXPDATE_INEXISTENT_CARD =
      "ERROR_GETCARDEXPDATE_INEXISTENT_CARD";

  public static final String ERROR_GETCARDEXPDATE_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_GETCARDEXPDATE_CARD_NOT_REGISTERED2PROVIDER";

  /** GET CARD CVV */
  public static final String ERROR_GETCARDCVV_INVALID_CARDID = "ERROR_GETCARDCVV_INVALID_CARDID";

  public static final String ERROR_GETCARDCVV_INEXISTENT_CARD = "ERROR_GETCARDCVV_INEXISTENT_CARD";

  public static final String ERROR_GETCARDCVV_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_GETCARDCVV_CARD_NOT_REGISTERED2PROVIDER";

  /** TRANSFER */
  public static final String ERROR_CARDTRANSFER_CARDID_REQUIRED =
      "ERROR_CARDTRANSFER_CARDID_REQUIRED";

  public static final String ERROR_CARDTRANSFER_CARDID_INVALID =
      "ERROR_CARDTRANSFER_CARDID_INVALID";

  public static final String ERROR_CARDTRANSFER_CURRENCY_REQUIRED =
      "ERROR_CARDTRANSFER_CURRENCY_REQUIRED";

  public static final String ERROR_CARDTRANSFER_CURRENCY_INVALID =
      "ERROR_CARDTRANSFER_CURRENCY_INVALID";

  public static final String ERROR_CARDTRANSFER_AMOUNT_REQUIRED =
      "ERROR_CARDTRANSFER_AMOUNT_REQUIRED";

  public static final String ERROR_CARDTRANSFER_AMOUNT_INVALID =
      "ERROR_CARDTRANSFER_AMOUNT_INVALID";

  public static final String ERROR_CARDTRANSFER_INEXISTENT_CARD =
      "ERROR_CARDTRANSFER_INEXISTENT_CARD";

  public static final String ERROR_CARDTRANSFER_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_CARDTRANSFER_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CARDTRANSFER_CARD_INVALID_STATUS =
      "ERROR_CARDTRANSFER_CARD_INVALID_STATUS";

  public static final String ERROR_CARDTRANSFER_CURRENCY_NOT_ALLOWED =
      "ERROR_CARDTRANSFER_CURRENCY_NOT_ALLOWED";

  public static final String ERROR_CARDTRANSFER_INEXISTENT_WALLET_CURRENCY =
      "ERROR_CARDTRANSFER_INEXISTENT_WALLET_CURRENCY";

  /** CARD SEND PIN */
  public static final String ERROR_SENDPIN_CARDID_REQUIRED = "ERROR_SENDPIN_CARDID_REQUIRED";

  public static final String ERROR_SENDPIN_CARDID_INVALID = "ERROR_SENDPIN_CARDID_INVALID";

  public static final String ERROR_SENDPIN_INEXISTENT_CARD = "ERROR_SENDPIN_INEXISTENT_CARD";

  public static final String ERROR_SENDPIN_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_SENDPIN_CARD_NOT_REGISTERED2PROVIDER";

  /** LOCK UNLOCK CARD */
  public static final String ERROR_LOCKUNLOCKCARD_CARDID_REQUIRED =
      "ERROR_LOCKUNLOCKCARD_CARDID_REQUIRED";

  public static final String ERROR_LOCKUNLOCKCARD_CARDID_INVALID =
      "ERROR_LOCKUNLOCKCARD_CARDID_INVALID";

  public static final String ERROR_LOCKUNLOCKCARD_OLDSTATUS_REQUIRED =
      "ERROR_LOCKUNLOCKCARD_OLDSTATUS_REQUIRED";

  public static final String ERROR_LOCKUNLOCKCARD_OLDSTATUS_INVALID =
      "ERROR_LOCKUNLOCKCARD_OLDSTATUS_INVALID";

  public static final String ERROR_LOCKUNLOCKCARD_NEWSTATUS_REQUIRED =
      "ERROR_LOCKUNLOCKCARD_NEWSTATUS_REQUIRED";

  public static final String ERROR_LOCKUNLOCKCARD_NEWSTATUS_INVALID =
      "ERROR_LOCKUNLOCKCARD_NEWSTATUS_INVALID";

  public static final String ERROR_LOCKUNLOCKCARD_INEXISTENT_CARD =
      "ERROR_LOCKUNLOCKCARD_INEXISTENT_CARD";

  public static final String ERROR_LOCKUNLOCKCARD_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_LOCKUNLOCKCARD_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_LOCKUNLOCKCARD_CARD_STATUS_MISSMATCH =
      "ERROR_LOCKUNLOCKCARD_CARD_STATUS_MISSMATCH";

  public static final String ERROR_LOCKUNLOCKCARD_CARD_STATUS_INVALID =
      "ERROR_LOCKUNLOCKCARD_CARD_STATUS_INVALID";

  /** UPDATE CARD */
  public static final String ERROR_UPDATEBANKCARD_CARDID_REQUIRED =
      "ERROR_UPDATEBANKCARD_CARDID_REQUIRED";

  public static final String ERROR_UPDATEBANKCARD_CARDID_INVALID =
      "ERROR_UPDATEBANKCARD_CARDID_INVALID";

  public static final String ERROR_UPDATEBANKCARD_INEXISTENT_CARD =
      "ERROR_UPDATEBANKCARD_INEXISTENT_CARD";

  public static final String ERROR_UPDATEBANKCARD_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_UPDATEBANKCARD_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_UPDATEBANKCARD_USERID_INEXISTENT =
      "ERROR_UPDATEBANKCARD_USERID_INEXISTENT";

  public static final String ERROR_UPDATEBANKCARD_USER_MISSING_ADDRESS =
      "ERROR_UPDATEBANKCARD_USER_MISSING_ADDRESS";

  public static final String ERROR_UPDATEBANKCARD_FIRSTNAME_REQUIRED =
      "ERROR_UPDATEBANKCARD_FIRSTNAME_REQUIRED";

  public static final String ERROR_UPDATEBANKCARD_FIRSTNAME_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_FIRSTNAME_MAXLENGTH";

  public static final String ERROR_UPDATEBANKCARD_LASTNAME_REQUIRED =
      "ERROR_UPDATEBANKCARD_LASTNAME_REQUIRED";

  public static final String ERROR_UPDATEBANKCARD_LASTNAME_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_LASTNAME_MAXLENGTH";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_LINE1_REQUIRED =
      "ERROR_UPDATEBANKCARD_ADDRESS_LINE1_REQUIRED";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_LINE1_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_ADDRESS_LINE1_MAXLENGTH";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_LINE2_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_ADDRESS_LINE2_MAXLENGTH";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_LINE3_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_ADDRESS_LINE3_MAXLENGTH";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_LINE4_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_ADDRESS_LINE3_MAXLENGTH";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_CITY_REQUIRED =
      "ERROR_UPDATEBANKCARD_ADDRESS_CITY_REQUIRED";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_CITY_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_ADDRESS_CITY_MAXLENGTH";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_COUNTY_REQUIRED =
      "ERROR_UPDATEBANKCARD_ADDRESS_COUNTY_REQUIRED";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_COUNTY_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_ADDRESS_COUNTY_MAXLENGTH";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_COUNTRY_REQUIRED =
      "ERROR_UPDATEBANKCARD_ADDRESS_COUNTRY_REQUIRED";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_COUNTRY_INVALID =
      "ERROR_UPDATEBANKCARD_ADDRESS_COUNTRY_INVALID";

  public static final String ERROR_UPDATEBANKCARD_ADDRESS_POSTALCODE_MAXLENGTH =
      "ERROR_UPDATEBANKCARD_ADDRESS_POSTALCODE_MAXLENGTH";

  /** PFS HOOK */
  public static final String ERROR_PFSHOOK_CARDID_REQUIRED = "ERROR_PFSHOOK_CARDID_REQUIRED";

  public static final String ERROR_PFSHOOK_CARDID_INVALID = "ERROR_PFSHOOK_CARDID_INVALID";

  public static final String ERROR_PFSHOOK_AMOUNT_REQUIRED = "ERROR_PFSHOOK_AMOUNT_REQUIRED";

  public static final String ERROR_PFSHOOK_AMOUNT_INVALID = "ERROR_PFSHOOK_AMOUNT_INVALID";

  public static final String ERROR_PFSHOOK_CURRENCY_REQUIRED = "ERROR_PFSHOOK_CURRENCY_REQUIRED";

  public static final String ERROR_PFSHOOK_CURRENCY_INVALID = "ERROR_PFSHOOK_CURRENCY_INVALID";

  public static final String ERROR_PFSHOOK_TRANSACTIONID_REQUIRED =
      "ERROR_PFSHOOK_TRANSACTIONID_REQUIRED";

  public static final String ERROR_PFSHOOK_TRANSACTIONID_INVALID =
      "ERROR_PFSHOOK_TRANSACTIONID_INVALID";

  public static final String ERROR_PFSHOOK_TRANSACTION_TYPE_REQUIRED =
      "ERROR_PFSHOOK_TRANSACTION_TYPE_REQUIRED";

  public static final String ERROR_PFSHOOK_TRANSACTION_TYPE_INVALID =
      "ERROR_PFSHOOK_TRANSACTION_TYPE_INVALID";

  public static final String ERROR_PFSHOOK_BALANCE_REQUIRED = "ERROR_PFSHOOK_BALANCE_REQUIRED";

  public static final String ERROR_PFSHOOK_BALANCE_INVALID = "ERROR_PFSHOOK_BALANCE_INVALID";

  /** BANK PAYMENT */
  public static final String ERROR_BANKPAYMENT_CARDID_REQUIRED =
      "ERROR_BANKPAYMENT_CARDID_REQUIRED";

  public static final String ERROR_BANKPAYMENT_CARDID_INVALID = "ERROR_BANKPAYMENT_CARDID_INVALID";

  public static final String ERROR_BANKPAYMENT_BENEFICIARYNAME_REQUIRED =
      "ERROR_BANKPAYMENT_BENEFICIARYNAME_REQUIRED";

  public static final String ERROR_BANKPAYMENT_BENEFICIARYNAME_MAXLENGTH =
      "ERROR_BANKPAYMENT_BENEFICIARYNAME_MAXLENGTH";

  public static final String ERROR_BANKPAYMENT_BENEFICIARYNAME_INVALID =
      "ERROR_BANKPAYMENT_BENEFICIARYNAME_INVALID";

  public static final String ERROR_BANKPAYMENT_ACCOUNTNUMBER_MINLENGTH =
      "ERROR_BANKPAYMENT_ACCOUNTNUMBER_MINLENGTH";

  public static final String ERROR_BANKPAYMENT_ACCOUNTNUMBER_MAXLENGTH =
      "ERROR_BANKPAYMENT_ACCOUNTNUMBER_MAXLENGTH";

  public static final String ERROR_BANKPAYMENT_ACCOUNTNUMBER_INVALID =
      "ERROR_BANKPAYMENT_ACCOUNTNUMBER_INVALID";

  public static final String ERROR_BANKPAYMENT_SORTCODE_MINLENGTH =
      "ERROR_BANKPAYMENT_SORTCODE_MINLENGTH";

  public static final String ERROR_BANKPAYMENT_SORTCODE_MAXLENGTH =
      "ERROR_BANKPAYMENT_SORTCODE_MAXLENGTH";

  public static final String ERROR_BANKPAYMENT_SORTCODE_INVALID =
      "ERROR_BANKPAYMENT_SORTCODE_INVALID";

  public static final String ERROR_BANKPAYMENT_PAYMENTAMOUNT_REQUIRED =
      "ERROR_BANKPAYMENT_PAYMENTAMOUNT_REQUIRED";

  public static final String ERROR_BANKPAYMENT_PAYMENTAMOUNT_INVALID =
      "ERROR_BANKPAYMENT_PAYMENTAMOUNT_INVALID";

  public static final String ERROR_BANKPAYMENT_REFERENCE_REQUIRED =
      "ERROR_BANKPAYMENT_REFERENCE_REQUIRED";

  public static final String ERROR_BANKPAYMENT_REFERENCE_MAXLENGTH =
      "ERROR_BANKPAYMENT_REFERENCE_MAXLENGTH";

  public static final String ERROR_BANKPAYMENT_REFERENCE_INVALID =
      "ERROR_BANKPAYMENT_REFERENCE_INVALID";

  public static final String ERROR_BANKPAYMENT_CREDITORIBAN_INVALID =
      "ERROR_BANKPAYMENT_CREDITORIBAN_INVALID";

  public static final String ERROR_BANKPAYMENT_CREDITORBIC_MAXLENGTH =
      "ERROR_BANKPAYMENT_CREDITORBIC_MAXLENGTH";

  public static final String ERROR_BANKPAYMENT_CREDITORBIC_MINLENGTH =
      "ERROR_BANKPAYMENT_CREDITORBIC_MINLENGTH";

  public static final String ERROR_BANKPAYMENT_CREDITORBIC_INVALID =
      "ERROR_BANKPAYMENT_CREDITORBIC_INVALID";

  public static final String ERROR_BANKPAYMENT_INEXISTENT_CARD =
      "ERROR_BANKPAYMENT_INEXISTENT_CARD";

  public static final String ERROR_BANKPAYMENT_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_BANKPAYMENT_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_BANKPAYMENT_CARD_INVALID_STATUS =
      "ERROR_BANKPAYMENT_CARD_INVALID_STATUS";

  /** GET FX QUOTE */
  public static final String ERROR_FXQUOTE_CARDID_REQUIRED = "ERROR_FXQUOTE_CARDID_REQUIRED";

  public static final String ERROR_FXQUOTE_CARDID_INVALID = "ERROR_FXQUOTE_CARDID_INVALID";

  public static final String ERROR_FXQUOTE_CURRENCYFROM_REQUIRED =
      "ERROR_FXQUOTE_CURRENCYFROM_REQUIRED";

  public static final String ERROR_FXQUOTE_CURRENCYFROM_INVALID =
      "ERROR_FXQUOTE_CURRENCYFROM_INVALID";

  public static final String ERROR_FXQUOTE_CURRENCYTO_REQUIRED =
      "ERROR_FXQUOTE_CURRENCYTO_REQUIRED";

  public static final String ERROR_FXQUOTE_CURRENCYTO_INVALID = "ERROR_FXQUOTE_CURRENCYTO_INVALID";

  public static final String ERROR_FXQUOTE_AMOUNT_REQUIRED = "ERROR_FXQUOTE_AMOUNT_REQUIRED";

  public static final String ERROR_FXQUOTE_AMOUNT_INVALID = "ERROR_FXQUOTE_AMOUNT_INVALID";

  public static final String ERROR_FXQUOTE_INEXISTENT_CARD = "ERROR_FXQUOTE_INEXISTENT_CARD";

  public static final String ERROR_FXQUOTE_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_FXQUOTE_CARD_NOT_REGISTERED2PROVIDER";

  /** REPLACE CARD */
  public static final String ERROR_REPLACECARD_CARDID_REQUIRED =
      "ERROR_REPLACECARD_CARDID_REQUIRED";

  public static final String ERROR_REPLACECARD_CARDID_INVALID = "ERROR_REPLACECARD_CARDID_INVALID";

  public static final String ERROR_REPLACECARD_REASON_REQUIRED =
      "ERROR_REPLACECARD_REASON_REQUIRED";

  public static final String ERROR_REPLACECARD_REASON_MAXLENGTH =
      "ERROR_REPLACECARD_REASON_MAXLENGTH";

  public static final String ERROR_REPLACECARD_REASON_INVALID = "ERROR_REPLACECARD_REASON_INVALID";

  public static final String ERROR_REPLACECARD_INEXISTENT_CARD =
      "ERROR_REPLACECARD_INEXISTENT_CARD";

  public static final String ERROR_REPLACECARD_CARD_INVALID_STATUS =
      "ERROR_REPLACECARD_CARD_INVALID_STATUS";

  public static final String ERROR_REPLACECARD_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_REPLACECARD_CARD_NOT_REGISTERED2PROVIDER";

  /** EXECUTE CARD WALLETS TRADE */
  public static final String ERROR_EXECUTECARDWALLETSTRADE_CARDID_REQUIRED =
      "ERROR_EXECUTECARDWALLETSTRADE_CARDID_REQUIRED";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_CARDID_INVALID =
      "ERROR_EXECUTECARDWALLETSTRADE_CARDID_INVALID";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_CURRENCYFROM_REQUIRED =
      "ERROR_EXECUTECARDWALLETSTRADE_CURRENCYFROM_REQUIRED";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_CURRENCYFROM_INVALID =
      "ERROR_EXECUTECARDWALLETSTRADE_CURRENCYFROM_INVALID";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_CURRENCYTO_REQUIRED =
      "ERROR_EXECUTECARDWALLETSTRADE_CURRENCYTO_REQUIRED";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_CURRENCYTO_INVALID =
      "ERROR_EXECUTECARDWALLETSTRADE_CURRENCYTO_INVALID";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_AMOUNT_REQUIRED =
      "ERROR_EXECUTECARDWALLETSTRADE_AMOUNT_REQUIRED";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_AMOUNT_INVALID =
      "ERROR_EXECUTECARDWALLETSTRADE_AMOUNT_INVALID";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_INEXISTENT_CARD =
      "ERROR_EXECUTECARDWALLETSTRADE_INEXISTENT_CARD";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_CARD_NOT_REGISTERED2PROVIDER =
      "ERROR_EXECUTECARDWALLETSTRADE_CARD_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_EXECUTECARDWALLETSTRADE_CARD_INVALID_STATUS =
      "ERROR_EXECUTECARDWALLETSTRADE_CARD_INVALID_STATUS";

  /** CREATE CARD REGISTRATION */
  public static final String ERROR_CREATECARDREGISTRATION_USER_INEXISTENT =
      "ERROR_CREATECARDREGISTRATION_USER_INEXISTENT";

  public static final String ERROR_CREATECARDREGISTRATION_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATECARDREGISTRATION_USER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATECARDREGISTRATION_USERID_REQUIRED =
      "ERROR_CREATECARDREGISTRATION_USERID_REQUIRED";

  public static final String ERROR_CREATECARDREGISTRATION_USERID_INVALID =
      "ERROR_CREATECARDREGISTRATION_USERID_INVALID";

  public static final String ERROR_CREATECARDREGISTRATION_CURRENCY_REQUIRED =
      "ERROR_CREATECARDREGISTRATION_CURRENCY_REQUIRED";

  public static final String ERROR_CREATECARDREGISTRATION_CURRENCY_INVALID =
      "ERROR_CREATECARDREGISTRATION_CURRENCY_INVALID";

  public static final String ERROR_CREATECARDREGISTRATION_CARDTYPE_INVALID =
      "ERROR_CREATECARDREGISTRATION_CARDTYPE_INVALID";

  public static final String ERROR_CREATECARDREGISTRATION_TAG_INVALID =
      "ERROR_CREATECARDREGISTRATION_TAG_INVALID";

  /** UPDATE CARD REGISTRATION */
  public static final String ERROR_UPDATECARDREGISTRATION_TAG_INVALID =
      "ERROR_UPDATECARDREGISTRATION_TAG_INVALID";

  public static final String ERROR_UPDATECARDREGISTRATION_REGISTRATIONDATA_INVALID =
      "ERROR_UPDATECARDREGISTRATION_REGISTRATIONDATA_INVALID";

  public static final String ERROR_UPDATECARDREGISTRATION_CARDREGISTRATIONID_INVALID =
      "ERROR_UPDATECARDREGISTRATION_CARDREGISTRATIONID_INVALID";

  public static final String ERROR_UPDATECARDREGISTRATION_USER_ID_REQUIRED =
      "ERROR_UPDATECARDREGISTRATION_USER_ID_REQUIRED";

  public static final String ERROR_UPDATECARDREGISTRATION_USER_ID_INVALID =
      "ERROR_UPDATECARDREGISTRATION_USER_ID_INVALID";

  public static final String ERROR_UPDATECARDREGISTRATION_USER_INEXISTENT =
      "ERROR_UPDATECARDREGISTRATION_USER_INEXISTENT";

  public static final String ERROR_UPDATECARDREGISTRATION_USER_NOT_REGISTERED2PROVIDER =
      "ERROR_UPDATECARDREGISTRATION_USER_NOT_REGISTERED2PROVIDER";

  /** CREATE DIRECT PAY IN */
  public static final String ERROR_CREATEDIRECTPAYIN_TAG_MAXLENGTH =
      "ERROR_CREATEDIRECTPAYIN_TAG_MAXLENGTH";

  public static final String ERROR_CREATEDIRECTPAYIN_CREDITWALLETID_REQUIRED =
      "ERROR_CREATEDIRECTPAYIN_CREDITWALLETID_REQUIRED";

  public static final String ERROR_CREATEDIRECTPAYIN_CREDITWALLETID_INVALID =
      "ERROR_CREATEDIRECTPAYIN_CREDITWALLETID_INVALID";

  public static final String ERROR_CREATEDIRECTPAYIN_DEBITFUNDS_REQUIRED =
      "ERROR_CREATEDIRECTPAYIN_DEBITFUNDS_REQUIRED";

  public static final String ERROR_CREATEDIRECTPAYIN_FEES_REQUIRED =
      "ERROR_CREATEDIRECTPAYIN_FEES_REQUIRED";

  public static final String ERROR_CREATEDIRECTPAYIN_FEEMODEL_REQUIRED =
      "ERROR_CREATEDIRECTPAYIN_FEEMODEL_REQUIRED";

  public static final String ERROR_CREATEDIRECTPAYIN_FEEMODEL_INVALID =
      "ERROR_CREATEDIRECTPAYIN_FEEMODEL_INVALID";

  public static final String ERROR_CREATEDIRECTPAYIN_RETURNURL_REQUIRED =
      "ERROR_CREATEDIRECTPAYIN_RETURNURL_REQUIRED";

  public static final String ERROR_CREATEDIRECTPAYIN_RETURNURL_MAXLENGTH =
      "ERROR_CREATEDIRECTPAYIN_RETURNURL_MAXLENGTH";

  public static final String ERROR_CREATEDIRECTPAYIN_SECUREMODERETURNURL_REQUIRED =
      "ERROR_CREATEDIRECTPAYIN_SECUREMODERETURNURL_REQUIRED";

  public static final String ERROR_CREATEDIRECTPAYIN_SECUREMODERETURNURL_MAXLENGTH =
      "ERROR_CREATEDIRECTPAYIN_SECUREMODERETURNURL_MAXLENGTH";

  public static final String ERROR_CREATEDIRECTPAYIN_SECUREMODERETURNURL_INVALID =
      "ERROR_CREATEDIRECTPAYIN_SECUREMODERETURNURL_INVALID";

  public static final String ERROR_CREATEDIRECTPAYIN_CARDID_REQUIRED =
      "ERROR_CREATEDIRECTPAYIN_CARDID_REQUIRED";

  public static final String ERROR_CREATEDIRECTPAYIN_CARDID_MAXLENGTH =
      "ERROR_CREATEDIRECTPAYIN_CARDID_MAXLENGTH";

  public static final String ERROR_CREATEDIRECTPAYIN_SECUREMODE_REQUIRED =
      "ERROR_CREATEDIRECTPAYIN_SECUREMODE_REQUIRED";

  public static final String ERROR_CREATEDIRECTPAYIN_SECUREMODE_INVALID =
      "ERROR_CREATEDIRECTPAYIN_SECUREMODE_INVALID";

  public static final String ERROR_CREATEDIRECTPAYIN_STATEMENTDESC_INVALID =
      "ERROR_CREATEDIRECTPAYIN_STATEMENTDESC_INVALID";

  public static final String ERROR_CREATEDIRECTPAYIN_STATEMENTDESC_MAXLENGTH =
      "ERROR_CREATEDIRECTPAYIN_STATEMENTDESC_MAXLENGTH";

  public static final String ERROR_CREATEDIRECTPAYIN_REQUEST_CURRENCY_MISSMATCH =
      "ERROR_CREATEDIRECTPAYIN_REQUEST_CURRENCY_MISSMATCH";

  public static final String ERROR_CREATEDIRECTPAYIN_REQUEST_AMOUNT_SMALLER_THAN_FEE =
      "ERROR_CREATEDIRECTPAYIN_REQUEST_AMOUNT_SMALLER_THAN_FEE";

  public static final String ERROR_CREATEDIRECTPAYIN_CREDITWALLET_INEXISTENT =
      "ERROR_CREATEDIRECTPAYIN_CREDITWALLET_INEXISTENT";

  public static final String ERROR_CREATEDIRECTPAYIN_CREDITWALLET_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEDIRECTPAYIN_CREDITWALLET_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEDIRECTPAYIN_REQUEST_CURRENCY_INVALID =
      "ERROR_CREATEDIRECTPAYIN_REQUEST_CURRENCY_INVALID";

  public static final String ERROR_CREATEDIRECTPAYIN_CREDITUSER_INEXISTENT =
      "ERROR_CREATEDIRECTPAYIN_CREDITUSER_INEXISTENT";

  public static final String ERROR_CREATEDIRECTPAYIN_CREDITUSER_NOT_REGISTERED2PROVIDER =
      "ERROR_CREATEDIRECTPAYIN_CREDITUSER_NOT_REGISTERED2PROVIDER";

  public static final String ERROR_CREATEDIRECTPAYIN_DEPOSITCARD_INEXISTENT =
      "ERROR_CREATEDIRECTPAYIN_DEPOSITCARD_INEXISTENT";

  /** GET PROVIDER TRANSACTION */
  public static final String ERROR_GETPROVIDERTRANSACTION_INVALID_TRANSACTIONID =
      "ERROR_GETPROVIDERTRANSACTION_INVALID_TRANSACTIONID";

  public static final String ERROR_GETPROVIDERTRANSACTION_INVALID_TYPE =
      "ERROR_GETPROVIDERTRANSACTION_INVALID_TYPE";

  public static final String ERROR_GETPROVIDERTRANSACTION_INVALID_NATURE =
      "ERROR_GETPROVIDERTRANSACTION_INVALID_NATURE";

  /** GET DEPOSIT CARD */
  public static final String ERROR_GETDEPOSITCARD_INVALID_PROVIDERCARDID =
      "ERROR_GETDEPOSITCARD_INVALID_PROVIDERCARDID";

  public static final String ERROR_GETDEPOSITCARD_INEXISTENT_DEPOSITCARD =
      "ERROR_GETDEPOSITCARD_INEXISTENT_DEPOSITCARD";

  /** DEACTIVATE DEPOSIT CARD */
  public static final String ERROR_DEACTIVATEDEPOSITCARD_INVALID_CARDID =
      "ERROR_DEACTIVATEDEPOSITCARD_INVALID_CARDID";

  public static final String ERROR_DEACTIVATEDEPOSITCARD_INEXISTENT_DEPOSITCARD =
      "ERROR_DEACTIVATEDEPOSITCARD_INEXISTENT_DEPOSITCARD";

  /** CREATE PAY IN REFUND */
  public static final String ERROR_CREATEPAYINREFUND_INVALID_PAYINID =
      "ERROR_CREATEPAYINREFUND_INVALID_PAYINID";

  public static final String ERROR_CREATEPAYINREFUND_INVALID_PAYINID_FORMAT =
      "ERROR_CREATEPAYINREFUND_INVALID_PAYINID_FORMAT";

  public static final String ERROR_CREATEPAYINREFUND_INEXISTENT_PAYIN =
      "ERROR_CREATEPAYINREFUND_INEXISTENT_PAYIN";

  public static final String ERROR_CREATEPAYINREFUND_INVALID_TYPE =
      "ERROR_CREATEPAYINREFUND_INVALID_TYPE";

  public static final String ERROR_CREATEPAYINREFUND_TAG_MAXLENGTH =
      "ERROR_CREATEPAYINREFUND_TAG_MAXLENGTH";

  public static final String ERROR_CREATEPAYINREFUND_CREDITWALLET_INEXISTENT =
      "ERROR_CREATEPAYINREFUND_CREDITWALLET_INEXISTENT";

  public static final String ERROR_CREATEPAYINREFUND_CREDITUSER_INEXISTENT =
      "ERROR_CREATEPAYINREFUND_CREDITUSER_INEXISTENT";

  /** GETPROCESSEDCALLBACK */
  public static final String ERROR_GETPROCESSEDCALLBACK_INVALID_CALLBACKID =
      "ERROR_GETPROCESSEDCALLBACK_INVALID_CALLBACKID";

  public static final String ERROR_GETPROCESSEDCALLBACK_INVALID_CALLBACKID_FORMAT =
      "ERROR_GETPROCESSEDCALLBACK_INVALID_CALLBACKID_FORMAT";

  public static final String ERROR_GETPROCESSEDCALLBACK_INEXISTENT_PROCESSEDCALLBACK =
      "ERROR_GETPROCESSEDCALLBACK_INEXISTENT_PROCESSEDCALLBACK";

  /** GETPAYINBYPROVIDERID */
  public static final String ERROR_GETPAYINBYPROVIDERID_INVALID_TRANSACTIONID =
      "ERROR_GETPAYINBYPROVIDERID_INVALID_TRANSACTIONID";

  public static final String ERROR_GETPAYINBYPROVIDERID_INEXISTENT_PAYIN =
      "ERROR_GETPAYINBYPROVIDERID_INEXISTENT_PAYIN";

  /** CREATEAVSDIRECTPAYIN */
  public static final String ERROR_CREATEAVSDIRECTPAYIN_BILLING_ADDRESS_REQUIRED =
      "ERROR_CREATEAVSDIRECTPAYIN_BILLING_ADDRESS_REQUIRED";

  /** GETDISPUTES */
  public static final String ERROR_GETDISPUTES_INVALID_USERID = "ERROR_GETDISPUTES_INVALID_USERID";

  public static final String ERROR_GETDISPUTES_INEXISTENT_USER =
      "ERROR_GETDISPUTES_INEXISTENT_USER";
}
