package ro.iss.lolopay.enums;

public enum NotificationType {
  PAYIN_NORMAL_CREATED,
  PAYIN_NORMAL_SUCCEEDED,
  PAYIN_NORMAL_FAILED, // PAYIN
  PAYOUT_NORMAL_CREATED,
  PAYOUT_NORMAL_SUCCEEDED,
  PAYOUT_NORMAL_FAILED, // PAYOUT
  TRANSFER_NORMAL_CREATED,
  TRANSFER_NORMAL_SUCCEEDED,
  TRANSFER_NORMAL_FAILED, // TRANSFER
  PAYIN_REFUND_CREATED,
  PAYIN_REFUND_SUCCEEDED,
  PAYIN_REFUND_FAILED, // REFUND PAYIN
  PAYOUT_REFUND_CREATED,
  PAYOUT_REFUND_SUCCEEDED,
  PAYOUT_REFUND_FAILED, // REFUND PAYOUT
  TRANSFER_REFUND_CREATED,
  TRANSFER_REFUND_SUCCEEDED,
  TRANSFER_REFUND_FAILED, // REFUND TRANSFER
  KYC_CREATED,
  KYC_VALIDATION_ASKED,
  KYC_SUCCEEDED,
  KYC_OUTDATED,
  KYC_FAILED, // KYC
  USER_KYC_LIGHT,
  USER_KYC_REGULAR,
  PAYIN_REPUDIATION_CREATED,
  PAYIN_REPUDIATION_SUCCEEDED,
  PAYIN_REPUDIATION_FAILED, // REPUDIATION
  DISPUTE_DOCUMENT_CREATED,
  DISPUTE_DOCUMENT_VALIDATION_ASKED,
  DISPUTE_DOCUMENT_SUCCEEDED,
  DISPUTE_DOCUMENT_FAILED,
  DISPUTE_CREATED,
  DISPUTE_SUBMITTED,
  DISPUTE_ACTION_REQUIRED,
  DISPUTE_FURTHER_ACTION_REQUIRED,
  DISPUTE_CLOSED,
  DISPUTE_SENT_TO_BANK, // DISPUTE
  TRANSFER_SETTLEMENT_CREATED,
  TRANSFER_SETTLEMENT_SUCCEEDED,
  TRANSFER_SETTLEMENT_FAILED, // SETTLEMENT
  MANDATE_CREATED,
  MANDATE_FAILED,
  MANDATE_ACTIVATED,
  MANDATE_SUBMITTED, // MANDATE
  PREAUTHORIZATION_PAYMENT_WAITING,
  PREAUTHORIZATION_PAYMENT_EXPIRED,
  PREAUTHORIZATION_PAYMENT_CANCELED,
  PREAUTHORIZATION_PAYMENT_VALIDATED, // PREAUTHORIZATION
  UBO_DECLARATION_CREATED,
  UBO_DECLARATION_VALIDATION_ASKED,
  UBO_DECLARATION_REFUSED,
  UBO_DECLARATION_INCOMPLETE,
  UBO_DECLARATION_VALIDATED, // UBO
  PFS_CALLBACK_TRANSACTION,
  PFS_CALLBACK_COMPANY_WALLET // PFS
}
